// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z
  .string()
  .regex(/^0x([0-9a-fA-F]{2})*$/)
  .transform((v) => v as `0x${string}`);
const BYTES32 = z
  .string()
  .regex(/^0x[0-9a-fA-F]{64}$/)
  .transform((v) => v as `0x${string}`);
const STRING = z.string();
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 8n) - 1n)
  .transform((b) => Number(b));

// === Function schemas ===

// VALIDATOR_AFK_BLOCKS()
export const VALIDATOR_AFK_BLOCKSSchema = z.tuple([]);

// _stakerMap(address)
export const _stakerMapSchema = z.tuple([ADDRESS]);

// addToDeposit(address)
export const addToDepositSchema = z.tuple([ADDRESS.describe('stakerAddress: address')]);

// amountStaked(address)
export const amountStakedSchema = z.tuple([ADDRESS.describe('staker: address')]);

// anyTrustFastConfirmer()
export const anyTrustFastConfirmerSchema = z.tuple([]);

// baseStake()
export const baseStakeSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// chainId()
export const chainIdSchema = z.tuple([]);

// challengeManager()
export const challengeManagerSchema = z.tuple([]);

// completeChallenge(uint256,address,address)
export const completeChallengeSchema = z.tuple([
  UINT256.describe('challengeIndex: uint256'),
  ADDRESS.describe('winningStaker: address'),
  ADDRESS.describe('losingStaker: address'),
]);

// confirmNextNode(bytes32,bytes32)
export const confirmNextNodeSchema = z.tuple([
  BYTES32.describe('blockHash: bytes32'),
  BYTES32.describe('sendRoot: bytes32'),
]);

// confirmPeriodBlocks()
export const confirmPeriodBlocksSchema = z.tuple([]);

// countStakedZombies(uint64)
export const countStakedZombiesSchema = z.tuple([UINT64.describe('nodeNum: uint64')]);

// countZombiesStakedOnChildren(uint64)
export const countZombiesStakedOnChildrenSchema = z.tuple([UINT64.describe('nodeNum: uint64')]);

// createChallenge(address[2],uint64[2],uint8[2],(bytes32[2],uint64[2])[2],uint64,bytes32,uint256[2],bytes32[2])
export const createChallengeSchema = z.tuple([
  z.array(ADDRESS).length(2).describe('address[2]'),
  z.array(UINT64).length(2).describe('uint64[2]'),
  z.array(UINT8).length(2).describe('uint8[2]'),
  z
    .array(
      z.strictObject({
        bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
        u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
      }),
    )
    .length(2)
    .describe('(bytes32[2],uint64[2])[2]'),
  UINT64.describe('numBlocks: uint64'),
  BYTES32.describe('secondExecutionHash: bytes32'),
  z.array(UINT256).length(2).describe('uint256[2]'),
  z.array(BYTES32).length(2).describe('bytes32[2]'),
]);

// createNitroMigrationGenesis((((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64))
export const createNitroMigrationGenesisSchema = z.tuple([
  z
    .strictObject({
      beforeState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
        })
        .describe('((bytes32[2],uint64[2]),uint8)'),
      afterState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
        })
        .describe('((bytes32[2],uint64[2]),uint8)'),
      numBlocks: UINT64.describe('numBlocks: uint64'),
    })
    .describe('(((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64)'),
]);

// currentChallenge(address)
export const currentChallengeSchema = z.tuple([ADDRESS.describe('staker: address')]);

// currentRequiredStake()
export const currentRequiredStakeSchema = z.tuple([]);

// extraChallengeTimeBlocks()
export const extraChallengeTimeBlocksSchema = z.tuple([]);

// fastConfirmNextNode(bytes32,bytes32,bytes32)
export const fastConfirmNextNodeSchema = z.tuple([
  BYTES32.describe('blockHash: bytes32'),
  BYTES32.describe('sendRoot: bytes32'),
  BYTES32.describe('nodeHash: bytes32'),
]);

// firstUnresolvedNode()
export const firstUnresolvedNodeSchema = z.tuple([]);

// forceConfirmNode(uint64,bytes32,bytes32)
export const forceConfirmNodeSchema = z.tuple([
  UINT64.describe('nodeNum: uint64'),
  BYTES32.describe('blockHash: bytes32'),
  BYTES32.describe('sendRoot: bytes32'),
]);

// forceCreateNode(uint64,uint256,(((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64),bytes32)
export const forceCreateNodeSchema = z.tuple([
  UINT64.describe('prevNode: uint64'),
  UINT256.describe('prevNodeInboxMaxCount: uint256'),
  z
    .strictObject({
      beforeState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
        })
        .describe('((bytes32[2],uint64[2]),uint8)'),
      afterState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
        })
        .describe('((bytes32[2],uint64[2]),uint8)'),
      numBlocks: UINT64.describe('numBlocks: uint64'),
    })
    .describe('(((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64)'),
  BYTES32.describe('expectedNodeHash: bytes32'),
]);

// forceRefundStaker(address[])
export const forceRefundStakerSchema = z.tuple([z.array(ADDRESS).describe('address[]')]);

// forceResolveChallenge(address[],address[])
export const forceResolveChallengeSchema = z.tuple([
  z.array(ADDRESS).describe('address[]'),
  z.array(ADDRESS).describe('address[]'),
]);

// getNode(uint64)
export const getNodeSchema = z.tuple([UINT64.describe('nodeNum: uint64')]);

// getNodeCreationBlockForLogLookup(uint64)
export const getNodeCreationBlockForLogLookupSchema = z.tuple([UINT64.describe('nodeNum: uint64')]);

// getStaker(address)
export const getStakerSchema = z.tuple([ADDRESS.describe('staker: address')]);

// getStakerAddress(uint64)
export const getStakerAddressSchema = z.tuple([UINT64.describe('stakerNum: uint64')]);

// inbox()
export const inboxSchema = z.tuple([]);

// isERC20Enabled()
export const isERC20EnabledSchema = z.tuple([]);

// isStaked(address)
export const isStakedSchema = z.tuple([ADDRESS.describe('staker: address')]);

// isStakedOnLatestConfirmed(address)
export const isStakedOnLatestConfirmedSchema = z.tuple([ADDRESS.describe('staker: address')]);

// isValidator(address)
export const isValidatorSchema = z.tuple([ADDRESS]);

// isZombie(address)
export const isZombieSchema = z.tuple([ADDRESS.describe('staker: address')]);

// lastStakeBlock()
export const lastStakeBlockSchema = z.tuple([]);

// latestConfirmed()
export const latestConfirmedSchema = z.tuple([]);

// latestNodeCreated()
export const latestNodeCreatedSchema = z.tuple([]);

// latestStakedNode(address)
export const latestStakedNodeSchema = z.tuple([ADDRESS.describe('staker: address')]);

// loserStakeEscrow()
export const loserStakeEscrowSchema = z.tuple([]);

// minimumAssertionPeriod()
export const minimumAssertionPeriodSchema = z.tuple([]);

// newStakeOnExistingNode(uint64,bytes32)
export const newStakeOnExistingNodeSchema = z.tuple([
  UINT64.describe('nodeNum: uint64'),
  BYTES32.describe('nodeHash: bytes32'),
]);

// newStakeOnNewNode((((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64),bytes32,uint256)
export const newStakeOnNewNodeSchema = z.tuple([
  z
    .strictObject({
      beforeState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
        })
        .describe('((bytes32[2],uint64[2]),uint8)'),
      afterState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
        })
        .describe('((bytes32[2],uint64[2]),uint8)'),
      numBlocks: UINT64.describe('numBlocks: uint64'),
    })
    .describe('(((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64)'),
  BYTES32.describe('expectedNodeHash: bytes32'),
  UINT256.describe('prevNodeInboxMaxCount: uint256'),
]);

// nodeHasStaker(uint64,address)
export const nodeHasStakerSchema = z.tuple([
  UINT64.describe('nodeNum: uint64'),
  ADDRESS.describe('staker: address'),
]);

// outbox()
export const outboxSchema = z.tuple([]);

// owner()
export const ownerSchema = z.tuple([]);

// pause()
export const pauseSchema = z.tuple([]);

// paused()
export const pausedSchema = z.tuple([]);

// proxiableUUID()
export const proxiableUUIDSchema = z.tuple([]);

// reduceDeposit(uint256)
export const reduceDepositSchema = z.tuple([UINT256.describe('target: uint256')]);

// rejectNextNode(address)
export const rejectNextNodeSchema = z.tuple([ADDRESS.describe('stakerAddress: address')]);

// removeOldOutbox(address)
export const removeOldOutboxSchema = z.tuple([ADDRESS.describe('_outbox: address')]);

// removeOldZombies(uint256)
export const removeOldZombiesSchema = z.tuple([UINT256.describe('startIndex: uint256')]);

// removeWhitelistAfterFork()
export const removeWhitelistAfterForkSchema = z.tuple([]);

// removeWhitelistAfterValidatorAfk()
export const removeWhitelistAfterValidatorAfkSchema = z.tuple([]);

// removeZombie(uint256,uint256)
export const removeZombieSchema = z.tuple([
  UINT256.describe('zombieNum: uint256'),
  UINT256.describe('maxNodes: uint256'),
]);

// requireUnresolved(uint256)
export const requireUnresolvedSchema = z.tuple([UINT256.describe('nodeNum: uint256')]);

// requireUnresolvedExists()
export const requireUnresolvedExistsSchema = z.tuple([]);

// requiredStake(uint256,uint64,uint64)
export const requiredStakeSchema = z.tuple([
  UINT256.describe('blockNumber: uint256'),
  UINT64.describe('firstUnresolvedNodeNum: uint64'),
  UINT64.describe('latestCreatedNode: uint64'),
]);

// resume()
export const resumeSchema = z.tuple([]);

// returnOldDeposit(address)
export const returnOldDepositSchema = z.tuple([ADDRESS.describe('stakerAddress: address')]);

// rollupDeploymentBlock()
export const rollupDeploymentBlockSchema = z.tuple([]);

// rollupEventInbox()
export const rollupEventInboxSchema = z.tuple([]);

// sequencerInbox()
export const sequencerInboxSchema = z.tuple([]);

// setAnyTrustFastConfirmer(address)
export const setAnyTrustFastConfirmerSchema = z.tuple([
  ADDRESS.describe('_anyTrustFastConfirmer: address'),
]);

// setBaseStake(uint256)
export const setBaseStakeSchema = z.tuple([UINT256.describe('newBaseStake: uint256')]);

// setConfirmPeriodBlocks(uint64)
export const setConfirmPeriodBlocksSchema = z.tuple([UINT64.describe('newConfirmPeriod: uint64')]);

// setDelayedInbox(address,bool)
export const setDelayedInboxSchema = z.tuple([
  ADDRESS.describe('_inbox: address'),
  BOOL.describe('_enabled: bool'),
]);

// setExtraChallengeTimeBlocks(uint64)
export const setExtraChallengeTimeBlocksSchema = z.tuple([
  UINT64.describe('newExtraTimeBlocks: uint64'),
]);

// setInbox(address)
export const setInboxSchema = z.tuple([ADDRESS.describe('newInbox: address')]);

// setLoserStakeEscrow(address)
export const setLoserStakeEscrowSchema = z.tuple([
  ADDRESS.describe('newLoserStakerEscrow: address'),
]);

// setMinimumAssertionPeriod(uint256)
export const setMinimumAssertionPeriodSchema = z.tuple([UINT256.describe('newPeriod: uint256')]);

// setOutbox(address)
export const setOutboxSchema = z.tuple([ADDRESS.describe('_outbox: address')]);

// setOwner(address)
export const setOwnerSchema = z.tuple([ADDRESS.describe('newOwner: address')]);

// setSequencerInbox(address)
export const setSequencerInboxSchema = z.tuple([ADDRESS.describe('_sequencerInbox: address')]);

// setStakeToken(address)
export const setStakeTokenSchema = z.tuple([ADDRESS.describe('newStakeToken: address')]);

// setValidator(address[],bool[])
export const setValidatorSchema = z.tuple([
  z.array(ADDRESS).describe('address[]'),
  z.array(BOOL).describe('bool[]'),
]);

// setValidatorWhitelistDisabled(bool)
export const setValidatorWhitelistDisabledSchema = z.tuple([
  BOOL.describe('_validatorWhitelistDisabled: bool'),
]);

// setWasmModuleRoot(bytes32)
export const setWasmModuleRootSchema = z.tuple([BYTES32.describe('newWasmModuleRoot: bytes32')]);

// stakeOnExistingNode(uint64,bytes32)
export const stakeOnExistingNodeSchema = z.tuple([
  UINT64.describe('nodeNum: uint64'),
  BYTES32.describe('nodeHash: bytes32'),
]);

// stakeOnNewNode((((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64),bytes32,uint256)
export const stakeOnNewNodeSchema = z.tuple([
  z
    .strictObject({
      beforeState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
        })
        .describe('((bytes32[2],uint64[2]),uint8)'),
      afterState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
        })
        .describe('((bytes32[2],uint64[2]),uint8)'),
      numBlocks: UINT64.describe('numBlocks: uint64'),
    })
    .describe('(((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64)'),
  BYTES32.describe('expectedNodeHash: bytes32'),
  UINT256.describe('prevNodeInboxMaxCount: uint256'),
]);

// stakeToken()
export const stakeTokenSchema = z.tuple([]);

// stakerCount()
export const stakerCountSchema = z.tuple([]);

// totalWithdrawableFunds()
export const totalWithdrawableFundsSchema = z.tuple([]);

// upgradeBeacon(address,address)
export const upgradeBeaconSchema = z.tuple([
  ADDRESS.describe('beacon: address'),
  ADDRESS.describe('newImplementation: address'),
]);

// upgradeSecondaryTo(address)
export const upgradeSecondaryToSchema = z.tuple([ADDRESS.describe('newImplementation: address')]);

// upgradeSecondaryToAndCall(address,bytes)
export const upgradeSecondaryToAndCallSchema = z.tuple([
  ADDRESS.describe('newImplementation: address'),
  BYTES.describe('data: bytes'),
]);

// upgradeTo(address)
export const upgradeToSchema = z.tuple([ADDRESS.describe('newImplementation: address')]);

// upgradeToAndCall(address,bytes)
export const upgradeToAndCallSchema = z.tuple([
  ADDRESS.describe('newImplementation: address'),
  BYTES.describe('data: bytes'),
]);

// validatorUtils()
export const validatorUtilsSchema = z.tuple([]);

// validatorWalletCreator()
export const validatorWalletCreatorSchema = z.tuple([]);

// validatorWhitelistDisabled()
export const validatorWhitelistDisabledSchema = z.tuple([]);

// wasmModuleRoot()
export const wasmModuleRootSchema = z.tuple([]);

// withdrawStakerFunds()
export const withdrawStakerFundsSchema = z.tuple([]);

// withdrawableFunds(address)
export const withdrawableFundsSchema = z.tuple([ADDRESS.describe('user: address')]);

// zombieAddress(uint256)
export const zombieAddressSchema = z.tuple([UINT256.describe('zombieNum: uint256')]);

// zombieCount()
export const zombieCountSchema = z.tuple([]);

// zombieLatestStakedNode(uint256)
export const zombieLatestStakedNodeSchema = z.tuple([UINT256.describe('zombieNum: uint256')]);

// === Schema table ===

export const schemas = {
  'VALIDATOR_AFK_BLOCKS': VALIDATOR_AFK_BLOCKSSchema,
  '_stakerMap': _stakerMapSchema,
  'addToDeposit': addToDepositSchema,
  'amountStaked': amountStakedSchema,
  'anyTrustFastConfirmer': anyTrustFastConfirmerSchema,
  'baseStake': baseStakeSchema,
  'bridge': bridgeSchema,
  'chainId': chainIdSchema,
  'challengeManager': challengeManagerSchema,
  'completeChallenge': completeChallengeSchema,
  'confirmNextNode': confirmNextNodeSchema,
  'confirmPeriodBlocks': confirmPeriodBlocksSchema,
  'countStakedZombies': countStakedZombiesSchema,
  'countZombiesStakedOnChildren': countZombiesStakedOnChildrenSchema,
  'createChallenge': createChallengeSchema,
  'createNitroMigrationGenesis': createNitroMigrationGenesisSchema,
  'currentChallenge': currentChallengeSchema,
  'currentRequiredStake': currentRequiredStakeSchema,
  'extraChallengeTimeBlocks': extraChallengeTimeBlocksSchema,
  'fastConfirmNextNode': fastConfirmNextNodeSchema,
  'firstUnresolvedNode': firstUnresolvedNodeSchema,
  'forceConfirmNode': forceConfirmNodeSchema,
  'forceCreateNode': forceCreateNodeSchema,
  'forceRefundStaker': forceRefundStakerSchema,
  'forceResolveChallenge': forceResolveChallengeSchema,
  'getNode': getNodeSchema,
  'getNodeCreationBlockForLogLookup': getNodeCreationBlockForLogLookupSchema,
  'getStaker': getStakerSchema,
  'getStakerAddress': getStakerAddressSchema,
  'inbox': inboxSchema,
  'isERC20Enabled': isERC20EnabledSchema,
  'isStaked': isStakedSchema,
  'isStakedOnLatestConfirmed': isStakedOnLatestConfirmedSchema,
  'isValidator': isValidatorSchema,
  'isZombie': isZombieSchema,
  'lastStakeBlock': lastStakeBlockSchema,
  'latestConfirmed': latestConfirmedSchema,
  'latestNodeCreated': latestNodeCreatedSchema,
  'latestStakedNode': latestStakedNodeSchema,
  'loserStakeEscrow': loserStakeEscrowSchema,
  'minimumAssertionPeriod': minimumAssertionPeriodSchema,
  'newStakeOnExistingNode': newStakeOnExistingNodeSchema,
  'newStakeOnNewNode': newStakeOnNewNodeSchema,
  'nodeHasStaker': nodeHasStakerSchema,
  'outbox': outboxSchema,
  'owner': ownerSchema,
  'pause': pauseSchema,
  'paused': pausedSchema,
  'proxiableUUID': proxiableUUIDSchema,
  'reduceDeposit': reduceDepositSchema,
  'rejectNextNode': rejectNextNodeSchema,
  'removeOldOutbox': removeOldOutboxSchema,
  'removeOldZombies': removeOldZombiesSchema,
  'removeWhitelistAfterFork': removeWhitelistAfterForkSchema,
  'removeWhitelistAfterValidatorAfk': removeWhitelistAfterValidatorAfkSchema,
  'removeZombie': removeZombieSchema,
  'requireUnresolved': requireUnresolvedSchema,
  'requireUnresolvedExists': requireUnresolvedExistsSchema,
  'requiredStake': requiredStakeSchema,
  'resume': resumeSchema,
  'returnOldDeposit': returnOldDepositSchema,
  'rollupDeploymentBlock': rollupDeploymentBlockSchema,
  'rollupEventInbox': rollupEventInboxSchema,
  'sequencerInbox': sequencerInboxSchema,
  'setAnyTrustFastConfirmer': setAnyTrustFastConfirmerSchema,
  'setBaseStake': setBaseStakeSchema,
  'setConfirmPeriodBlocks': setConfirmPeriodBlocksSchema,
  'setDelayedInbox': setDelayedInboxSchema,
  'setExtraChallengeTimeBlocks': setExtraChallengeTimeBlocksSchema,
  'setInbox': setInboxSchema,
  'setLoserStakeEscrow': setLoserStakeEscrowSchema,
  'setMinimumAssertionPeriod': setMinimumAssertionPeriodSchema,
  'setOutbox': setOutboxSchema,
  'setOwner': setOwnerSchema,
  'setSequencerInbox': setSequencerInboxSchema,
  'setStakeToken': setStakeTokenSchema,
  'setValidator': setValidatorSchema,
  'setValidatorWhitelistDisabled': setValidatorWhitelistDisabledSchema,
  'setWasmModuleRoot': setWasmModuleRootSchema,
  'stakeOnExistingNode': stakeOnExistingNodeSchema,
  'stakeOnNewNode': stakeOnNewNodeSchema,
  'stakeToken': stakeTokenSchema,
  'stakerCount': stakerCountSchema,
  'totalWithdrawableFunds': totalWithdrawableFundsSchema,
  'upgradeBeacon': upgradeBeaconSchema,
  'upgradeSecondaryTo': upgradeSecondaryToSchema,
  'upgradeSecondaryToAndCall': upgradeSecondaryToAndCallSchema,
  'upgradeTo': upgradeToSchema,
  'upgradeToAndCall': upgradeToAndCallSchema,
  'validatorUtils': validatorUtilsSchema,
  'validatorWalletCreator': validatorWalletCreatorSchema,
  'validatorWhitelistDisabled': validatorWhitelistDisabledSchema,
  'wasmModuleRoot': wasmModuleRootSchema,
  'withdrawStakerFunds': withdrawStakerFundsSchema,
  'withdrawableFunds': withdrawableFundsSchema,
  'zombieAddress': zombieAddressSchema,
  'zombieCount': zombieCountSchema,
  'zombieLatestStakedNode': zombieLatestStakedNodeSchema,
  'VALIDATOR_AFK_BLOCKS()': VALIDATOR_AFK_BLOCKSSchema,
  '_stakerMap(address)': _stakerMapSchema,
  'addToDeposit(address)': addToDepositSchema,
  'amountStaked(address)': amountStakedSchema,
  'anyTrustFastConfirmer()': anyTrustFastConfirmerSchema,
  'baseStake()': baseStakeSchema,
  'bridge()': bridgeSchema,
  'chainId()': chainIdSchema,
  'challengeManager()': challengeManagerSchema,
  'completeChallenge(uint256,address,address)': completeChallengeSchema,
  'confirmNextNode(bytes32,bytes32)': confirmNextNodeSchema,
  'confirmPeriodBlocks()': confirmPeriodBlocksSchema,
  'countStakedZombies(uint64)': countStakedZombiesSchema,
  'countZombiesStakedOnChildren(uint64)': countZombiesStakedOnChildrenSchema,
  'createChallenge(address[2],uint64[2],uint8[2],(bytes32[2],uint64[2])[2],uint64,bytes32,uint256[2],bytes32[2])':
    createChallengeSchema,
  'createNitroMigrationGenesis((((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64))':
    createNitroMigrationGenesisSchema,
  'currentChallenge(address)': currentChallengeSchema,
  'currentRequiredStake()': currentRequiredStakeSchema,
  'extraChallengeTimeBlocks()': extraChallengeTimeBlocksSchema,
  'fastConfirmNextNode(bytes32,bytes32,bytes32)': fastConfirmNextNodeSchema,
  'firstUnresolvedNode()': firstUnresolvedNodeSchema,
  'forceConfirmNode(uint64,bytes32,bytes32)': forceConfirmNodeSchema,
  'forceCreateNode(uint64,uint256,(((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64),bytes32)':
    forceCreateNodeSchema,
  'forceRefundStaker(address[])': forceRefundStakerSchema,
  'forceResolveChallenge(address[],address[])': forceResolveChallengeSchema,
  'getNode(uint64)': getNodeSchema,
  'getNodeCreationBlockForLogLookup(uint64)': getNodeCreationBlockForLogLookupSchema,
  'getStaker(address)': getStakerSchema,
  'getStakerAddress(uint64)': getStakerAddressSchema,
  'inbox()': inboxSchema,
  'initialize((uint64,uint64,address,uint256,bytes32,address,address,uint256,string,uint64,(uint256,uint256,uint256,uint256)),(address,address,address,address,address,address,address,address,address,address))':
    z.tuple([
      z
        .strictObject({
          confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
          extraChallengeTimeBlocks: UINT64.describe('extraChallengeTimeBlocks: uint64'),
          stakeToken: ADDRESS.describe('stakeToken: address'),
          baseStake: UINT256.describe('baseStake: uint256'),
          wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
          owner: ADDRESS.describe('owner: address'),
          loserStakeEscrow: ADDRESS.describe('loserStakeEscrow: address'),
          chainId: UINT256.describe('chainId: uint256'),
          chainConfig: STRING.describe('chainConfig: string'),
          genesisBlockNum: UINT64.describe('genesisBlockNum: uint64'),
          sequencerInboxMaxTimeVariation: z
            .strictObject({
              delayBlocks: UINT256.describe('delayBlocks: uint256'),
              futureBlocks: UINT256.describe('futureBlocks: uint256'),
              delaySeconds: UINT256.describe('delaySeconds: uint256'),
              futureSeconds: UINT256.describe('futureSeconds: uint256'),
            })
            .describe('(uint256,uint256,uint256,uint256)'),
        })
        .describe(
          '(uint64,uint64,address,uint256,bytes32,address,address,uint256,string,uint64,(uint256,uint256,uint256,uint256))',
        ),
      z
        .strictObject({
          bridge: ADDRESS.describe('bridge: address'),
          sequencerInbox: ADDRESS.describe('sequencerInbox: address'),
          inbox: ADDRESS.describe('inbox: address'),
          outbox: ADDRESS.describe('outbox: address'),
          rollupEventInbox: ADDRESS.describe('rollupEventInbox: address'),
          challengeManager: ADDRESS.describe('challengeManager: address'),
          rollupAdminLogic: ADDRESS.describe('rollupAdminLogic: address'),
          rollupUserLogic: ADDRESS.describe('rollupUserLogic: address'),
          validatorUtils: ADDRESS.describe('validatorUtils: address'),
          validatorWalletCreator: ADDRESS.describe('validatorWalletCreator: address'),
        })
        .describe(
          '(address,address,address,address,address,address,address,address,address,address)',
        ),
    ]),
  'initialize(address)': z.tuple([ADDRESS.describe('_stakeToken: address')]),
  'isERC20Enabled()': isERC20EnabledSchema,
  'isStaked(address)': isStakedSchema,
  'isStakedOnLatestConfirmed(address)': isStakedOnLatestConfirmedSchema,
  'isValidator(address)': isValidatorSchema,
  'isZombie(address)': isZombieSchema,
  'lastStakeBlock()': lastStakeBlockSchema,
  'latestConfirmed()': latestConfirmedSchema,
  'latestNodeCreated()': latestNodeCreatedSchema,
  'latestStakedNode(address)': latestStakedNodeSchema,
  'loserStakeEscrow()': loserStakeEscrowSchema,
  'minimumAssertionPeriod()': minimumAssertionPeriodSchema,
  'newStakeOnExistingNode(uint64,bytes32)': newStakeOnExistingNodeSchema,
  'newStakeOnNewNode((((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64),bytes32,uint256)':
    newStakeOnNewNodeSchema,
  'nodeHasStaker(uint64,address)': nodeHasStakerSchema,
  'outbox()': outboxSchema,
  'owner()': ownerSchema,
  'pause()': pauseSchema,
  'paused()': pausedSchema,
  'proxiableUUID()': proxiableUUIDSchema,
  'reduceDeposit(uint256)': reduceDepositSchema,
  'rejectNextNode(address)': rejectNextNodeSchema,
  'removeOldOutbox(address)': removeOldOutboxSchema,
  'removeOldZombies(uint256)': removeOldZombiesSchema,
  'removeWhitelistAfterFork()': removeWhitelistAfterForkSchema,
  'removeWhitelistAfterValidatorAfk()': removeWhitelistAfterValidatorAfkSchema,
  'removeZombie(uint256,uint256)': removeZombieSchema,
  'requireUnresolved(uint256)': requireUnresolvedSchema,
  'requireUnresolvedExists()': requireUnresolvedExistsSchema,
  'requiredStake(uint256,uint64,uint64)': requiredStakeSchema,
  'resume()': resumeSchema,
  'returnOldDeposit(address)': returnOldDepositSchema,
  'rollupDeploymentBlock()': rollupDeploymentBlockSchema,
  'rollupEventInbox()': rollupEventInboxSchema,
  'sequencerInbox()': sequencerInboxSchema,
  'setAnyTrustFastConfirmer(address)': setAnyTrustFastConfirmerSchema,
  'setBaseStake(uint256)': setBaseStakeSchema,
  'setConfirmPeriodBlocks(uint64)': setConfirmPeriodBlocksSchema,
  'setDelayedInbox(address,bool)': setDelayedInboxSchema,
  'setExtraChallengeTimeBlocks(uint64)': setExtraChallengeTimeBlocksSchema,
  'setInbox(address)': setInboxSchema,
  'setLoserStakeEscrow(address)': setLoserStakeEscrowSchema,
  'setMinimumAssertionPeriod(uint256)': setMinimumAssertionPeriodSchema,
  'setOutbox(address)': setOutboxSchema,
  'setOwner(address)': setOwnerSchema,
  'setSequencerInbox(address)': setSequencerInboxSchema,
  'setStakeToken(address)': setStakeTokenSchema,
  'setValidator(address[],bool[])': setValidatorSchema,
  'setValidatorWhitelistDisabled(bool)': setValidatorWhitelistDisabledSchema,
  'setWasmModuleRoot(bytes32)': setWasmModuleRootSchema,
  'stakeOnExistingNode(uint64,bytes32)': stakeOnExistingNodeSchema,
  'stakeOnNewNode((((bytes32[2],uint64[2]),uint8),((bytes32[2],uint64[2]),uint8),uint64),bytes32,uint256)':
    stakeOnNewNodeSchema,
  'stakeToken()': stakeTokenSchema,
  'stakerCount()': stakerCountSchema,
  'totalWithdrawableFunds()': totalWithdrawableFundsSchema,
  'upgradeBeacon(address,address)': upgradeBeaconSchema,
  'upgradeSecondaryTo(address)': upgradeSecondaryToSchema,
  'upgradeSecondaryToAndCall(address,bytes)': upgradeSecondaryToAndCallSchema,
  'upgradeTo(address)': upgradeToSchema,
  'upgradeToAndCall(address,bytes)': upgradeToAndCallSchema,
  'validatorUtils()': validatorUtilsSchema,
  'validatorWalletCreator()': validatorWalletCreatorSchema,
  'validatorWhitelistDisabled()': validatorWhitelistDisabledSchema,
  'wasmModuleRoot()': wasmModuleRootSchema,
  'withdrawStakerFunds()': withdrawStakerFundsSchema,
  'withdrawableFunds(address)': withdrawableFundsSchema,
  'zombieAddress(uint256)': zombieAddressSchema,
  'zombieCount()': zombieCountSchema,
  'zombieLatestStakedNode(uint256)': zombieLatestStakedNodeSchema,
} as const;
