// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z
  .string()
  .regex(/^0x([0-9a-fA-F]{2})*$/)
  .transform((v) => v as `0x${string}`);
const BYTES32 = z
  .string()
  .regex(/^0x[0-9a-fA-F]{64}$/)
  .transform((v) => v as `0x${string}`);
const STRING = z.string();
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 8n) - 1n)
  .transform((b) => Number(b));

// === Function schemas ===

// _stakerMap(address)
export const _stakerMapSchema = z.tuple([ADDRESS]);

// addToDeposit(address,address,uint256)
export const addToDepositSchema = z.tuple([
  ADDRESS.describe('stakerAddress: address'),
  ADDRESS.describe('expectedWithdrawalAddress: address'),
  UINT256.describe('tokenAmount: uint256'),
]);

// amountStaked(address)
export const amountStakedSchema = z.tuple([ADDRESS.describe('staker: address')]);

// anyTrustFastConfirmer()
export const anyTrustFastConfirmerSchema = z.tuple([]);

// baseStake()
export const baseStakeSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// chainId()
export const chainIdSchema = z.tuple([]);

// challengeGracePeriodBlocks()
export const challengeGracePeriodBlocksSchema = z.tuple([]);

// challengeManager()
export const challengeManagerSchema = z.tuple([]);

// computeAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)
export const computeAssertionHashSchema = z.tuple([
  BYTES32.describe('prevAssertionHash: bytes32'),
  z
    .strictObject({
      globalState: z
        .strictObject({
          bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
          u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
        })
        .describe('(bytes32[2],uint64[2])'),
      machineStatus: UINT8.describe('machineStatus: uint8'),
      endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
    })
    .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
  BYTES32.describe('inboxAcc: bytes32'),
]);

// confirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,(bytes32,uint256,address,uint64,uint64),bytes32)
export const confirmAssertionSchema = z.tuple([
  BYTES32.describe('assertionHash: bytes32'),
  BYTES32.describe('prevAssertionHash: bytes32'),
  z
    .strictObject({
      globalState: z
        .strictObject({
          bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
          u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
        })
        .describe('(bytes32[2],uint64[2])'),
      machineStatus: UINT8.describe('machineStatus: uint8'),
      endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
    })
    .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
  BYTES32.describe('winningEdgeId: bytes32'),
  z
    .strictObject({
      wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
      requiredStake: UINT256.describe('requiredStake: uint256'),
      challengeManager: ADDRESS.describe('challengeManager: address'),
      confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
      nextInboxPosition: UINT64.describe('nextInboxPosition: uint64'),
    })
    .describe('(bytes32,uint256,address,uint64,uint64)'),
  BYTES32.describe('inboxAcc: bytes32'),
]);

// confirmPeriodBlocks()
export const confirmPeriodBlocksSchema = z.tuple([]);

// fastConfirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)
export const fastConfirmAssertionSchema = z.tuple([
  BYTES32.describe('assertionHash: bytes32'),
  BYTES32.describe('parentAssertionHash: bytes32'),
  z
    .strictObject({
      globalState: z
        .strictObject({
          bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
          u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
        })
        .describe('(bytes32[2],uint64[2])'),
      machineStatus: UINT8.describe('machineStatus: uint8'),
      endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
    })
    .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
  BYTES32.describe('inboxAcc: bytes32'),
]);

// fastConfirmNewAssertion(((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)
export const fastConfirmNewAssertionSchema = z.tuple([
  z
    .strictObject({
      beforeStateData: z
        .strictObject({
          prevPrevAssertionHash: BYTES32.describe('prevPrevAssertionHash: bytes32'),
          sequencerBatchAcc: BYTES32.describe('sequencerBatchAcc: bytes32'),
          configData: z
            .strictObject({
              wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
              requiredStake: UINT256.describe('requiredStake: uint256'),
              challengeManager: ADDRESS.describe('challengeManager: address'),
              confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
              nextInboxPosition: UINT64.describe('nextInboxPosition: uint64'),
            })
            .describe('(bytes32,uint256,address,uint64,uint64)'),
        })
        .describe('(bytes32,bytes32,(bytes32,uint256,address,uint64,uint64))'),
      beforeState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
          endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
        })
        .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
      afterState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
          endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
        })
        .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
    })
    .describe(
      '((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32))',
    ),
  BYTES32.describe('expectedAssertionHash: bytes32'),
]);

// forceConfirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)
export const forceConfirmAssertionSchema = z.tuple([
  BYTES32.describe('assertionHash: bytes32'),
  BYTES32.describe('parentAssertionHash: bytes32'),
  z
    .strictObject({
      globalState: z
        .strictObject({
          bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
          u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
        })
        .describe('(bytes32[2],uint64[2])'),
      machineStatus: UINT8.describe('machineStatus: uint8'),
      endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
    })
    .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
  BYTES32.describe('inboxAcc: bytes32'),
]);

// forceCreateAssertion(bytes32,((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)
export const forceCreateAssertionSchema = z.tuple([
  BYTES32.describe('prevAssertionHash: bytes32'),
  z
    .strictObject({
      beforeStateData: z
        .strictObject({
          prevPrevAssertionHash: BYTES32.describe('prevPrevAssertionHash: bytes32'),
          sequencerBatchAcc: BYTES32.describe('sequencerBatchAcc: bytes32'),
          configData: z
            .strictObject({
              wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
              requiredStake: UINT256.describe('requiredStake: uint256'),
              challengeManager: ADDRESS.describe('challengeManager: address'),
              confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
              nextInboxPosition: UINT64.describe('nextInboxPosition: uint64'),
            })
            .describe('(bytes32,uint256,address,uint64,uint64)'),
        })
        .describe('(bytes32,bytes32,(bytes32,uint256,address,uint64,uint64))'),
      beforeState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
          endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
        })
        .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
      afterState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
          endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
        })
        .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
    })
    .describe(
      '((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32))',
    ),
  BYTES32.describe('expectedAssertionHash: bytes32'),
]);

// forceRefundStaker(address[])
export const forceRefundStakerSchema = z.tuple([z.array(ADDRESS).describe('address[]')]);

// genesisAssertionHash()
export const genesisAssertionHashSchema = z.tuple([]);

// getAssertion(bytes32)
export const getAssertionSchema = z.tuple([BYTES32.describe('assertionHash: bytes32')]);

// getAssertionCreationBlockForLogLookup(bytes32)
export const getAssertionCreationBlockForLogLookupSchema = z.tuple([
  BYTES32.describe('assertionHash: bytes32'),
]);

// getFirstChildCreationBlock(bytes32)
export const getFirstChildCreationBlockSchema = z.tuple([
  BYTES32.describe('assertionHash: bytes32'),
]);

// getSecondChildCreationBlock(bytes32)
export const getSecondChildCreationBlockSchema = z.tuple([
  BYTES32.describe('assertionHash: bytes32'),
]);

// getStaker(address)
export const getStakerSchema = z.tuple([ADDRESS.describe('staker: address')]);

// getStakerAddress(uint64)
export const getStakerAddressSchema = z.tuple([UINT64.describe('stakerNum: uint64')]);

// getValidators()
export const getValidatorsSchema = z.tuple([]);

// inbox()
export const inboxSchema = z.tuple([]);

// isFirstChild(bytes32)
export const isFirstChildSchema = z.tuple([BYTES32.describe('assertionHash: bytes32')]);

// isPending(bytes32)
export const isPendingSchema = z.tuple([BYTES32.describe('assertionHash: bytes32')]);

// isStaked(address)
export const isStakedSchema = z.tuple([ADDRESS.describe('staker: address')]);

// isValidator(address)
export const isValidatorSchema = z.tuple([ADDRESS.describe('validator: address')]);

// latestConfirmed()
export const latestConfirmedSchema = z.tuple([]);

// latestStakedAssertion(address)
export const latestStakedAssertionSchema = z.tuple([ADDRESS.describe('staker: address')]);

// loserStakeEscrow()
export const loserStakeEscrowSchema = z.tuple([]);

// minimumAssertionPeriod()
export const minimumAssertionPeriodSchema = z.tuple([]);

// newStake(uint256,address)
export const newStakeSchema = z.tuple([
  UINT256.describe('tokenAmount: uint256'),
  ADDRESS.describe('_withdrawalAddress: address'),
]);

// outbox()
export const outboxSchema = z.tuple([]);

// owner()
export const ownerSchema = z.tuple([]);

// pause()
export const pauseSchema = z.tuple([]);

// paused()
export const pausedSchema = z.tuple([]);

// proxiableUUID()
export const proxiableUUIDSchema = z.tuple([]);

// reduceDeposit(uint256)
export const reduceDepositSchema = z.tuple([UINT256.describe('target: uint256')]);

// removeOldOutbox(address)
export const removeOldOutboxSchema = z.tuple([ADDRESS.describe('_outbox: address')]);

// removeWhitelistAfterFork()
export const removeWhitelistAfterForkSchema = z.tuple([]);

// removeWhitelistAfterValidatorAfk()
export const removeWhitelistAfterValidatorAfkSchema = z.tuple([]);

// resume()
export const resumeSchema = z.tuple([]);

// returnOldDeposit()
export const returnOldDepositSchema = z.tuple([]);

// returnOldDepositFor(address)
export const returnOldDepositForSchema = z.tuple([ADDRESS.describe('stakerAddress: address')]);

// rollupDeploymentBlock()
export const rollupDeploymentBlockSchema = z.tuple([]);

// rollupEventInbox()
export const rollupEventInboxSchema = z.tuple([]);

// sequencerInbox()
export const sequencerInboxSchema = z.tuple([]);

// setAnyTrustFastConfirmer(address)
export const setAnyTrustFastConfirmerSchema = z.tuple([
  ADDRESS.describe('_anyTrustFastConfirmer: address'),
]);

// setBaseStake(uint256)
export const setBaseStakeSchema = z.tuple([UINT256.describe('newBaseStake: uint256')]);

// setChallengeManager(address)
export const setChallengeManagerSchema = z.tuple([ADDRESS.describe('_challengeManager: address')]);

// setConfirmPeriodBlocks(uint64)
export const setConfirmPeriodBlocksSchema = z.tuple([UINT64.describe('newConfirmPeriod: uint64')]);

// setDelayedInbox(address,bool)
export const setDelayedInboxSchema = z.tuple([
  ADDRESS.describe('_inbox: address'),
  BOOL.describe('_enabled: bool'),
]);

// setInbox(address)
export const setInboxSchema = z.tuple([ADDRESS.describe('newInbox: address')]);

// setLoserStakeEscrow(address)
export const setLoserStakeEscrowSchema = z.tuple([
  ADDRESS.describe('newLoserStakerEscrow: address'),
]);

// setMinimumAssertionPeriod(uint256)
export const setMinimumAssertionPeriodSchema = z.tuple([UINT256.describe('newPeriod: uint256')]);

// setOutbox(address)
export const setOutboxSchema = z.tuple([ADDRESS.describe('_outbox: address')]);

// setOwner(address)
export const setOwnerSchema = z.tuple([ADDRESS.describe('newOwner: address')]);

// setSequencerInbox(address)
export const setSequencerInboxSchema = z.tuple([ADDRESS.describe('_sequencerInbox: address')]);

// setValidator(address[],bool[])
export const setValidatorSchema = z.tuple([
  z.array(ADDRESS).describe('address[]'),
  z.array(BOOL).describe('bool[]'),
]);

// setValidatorAfkBlocks(uint64)
export const setValidatorAfkBlocksSchema = z.tuple([UINT64.describe('newAfkBlocks: uint64')]);

// setValidatorWhitelistDisabled(bool)
export const setValidatorWhitelistDisabledSchema = z.tuple([
  BOOL.describe('_validatorWhitelistDisabled: bool'),
]);

// setWasmModuleRoot(bytes32)
export const setWasmModuleRootSchema = z.tuple([BYTES32.describe('newWasmModuleRoot: bytes32')]);

// stakeOnNewAssertion(((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)
export const stakeOnNewAssertionSchema = z.tuple([
  z
    .strictObject({
      beforeStateData: z
        .strictObject({
          prevPrevAssertionHash: BYTES32.describe('prevPrevAssertionHash: bytes32'),
          sequencerBatchAcc: BYTES32.describe('sequencerBatchAcc: bytes32'),
          configData: z
            .strictObject({
              wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
              requiredStake: UINT256.describe('requiredStake: uint256'),
              challengeManager: ADDRESS.describe('challengeManager: address'),
              confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
              nextInboxPosition: UINT64.describe('nextInboxPosition: uint64'),
            })
            .describe('(bytes32,uint256,address,uint64,uint64)'),
        })
        .describe('(bytes32,bytes32,(bytes32,uint256,address,uint64,uint64))'),
      beforeState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
          endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
        })
        .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
      afterState: z
        .strictObject({
          globalState: z
            .strictObject({
              bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
              u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
            })
            .describe('(bytes32[2],uint64[2])'),
          machineStatus: UINT8.describe('machineStatus: uint8'),
          endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
        })
        .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
    })
    .describe(
      '((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32))',
    ),
  BYTES32.describe('expectedAssertionHash: bytes32'),
]);

// stakeToken()
export const stakeTokenSchema = z.tuple([]);

// stakerCount()
export const stakerCountSchema = z.tuple([]);

// totalWithdrawableFunds()
export const totalWithdrawableFundsSchema = z.tuple([]);

// upgradeSecondaryTo(address)
export const upgradeSecondaryToSchema = z.tuple([ADDRESS.describe('newImplementation: address')]);

// upgradeSecondaryToAndCall(address,bytes)
export const upgradeSecondaryToAndCallSchema = z.tuple([
  ADDRESS.describe('newImplementation: address'),
  BYTES.describe('data: bytes'),
]);

// upgradeTo(address)
export const upgradeToSchema = z.tuple([ADDRESS.describe('newImplementation: address')]);

// upgradeToAndCall(address,bytes)
export const upgradeToAndCallSchema = z.tuple([
  ADDRESS.describe('newImplementation: address'),
  BYTES.describe('data: bytes'),
]);

// validateAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32)
export const validateAssertionHashSchema = z.tuple([
  BYTES32.describe('assertionHash: bytes32'),
  z
    .strictObject({
      globalState: z
        .strictObject({
          bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
          u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
        })
        .describe('(bytes32[2],uint64[2])'),
      machineStatus: UINT8.describe('machineStatus: uint8'),
      endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
    })
    .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
  BYTES32.describe('prevAssertionHash: bytes32'),
  BYTES32.describe('inboxAcc: bytes32'),
]);

// validateConfig(bytes32,(bytes32,uint256,address,uint64,uint64))
export const validateConfigSchema = z.tuple([
  BYTES32.describe('assertionHash: bytes32'),
  z
    .strictObject({
      wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
      requiredStake: UINT256.describe('requiredStake: uint256'),
      challengeManager: ADDRESS.describe('challengeManager: address'),
      confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
      nextInboxPosition: UINT64.describe('nextInboxPosition: uint64'),
    })
    .describe('(bytes32,uint256,address,uint64,uint64)'),
]);

// validatorAfkBlocks()
export const validatorAfkBlocksSchema = z.tuple([]);

// validatorWalletCreator()
export const validatorWalletCreatorSchema = z.tuple([]);

// validatorWhitelistDisabled()
export const validatorWhitelistDisabledSchema = z.tuple([]);

// wasmModuleRoot()
export const wasmModuleRootSchema = z.tuple([]);

// withdrawStakerFunds()
export const withdrawStakerFundsSchema = z.tuple([]);

// withdrawableFunds(address)
export const withdrawableFundsSchema = z.tuple([ADDRESS.describe('user: address')]);

// withdrawalAddress(address)
export const withdrawalAddressSchema = z.tuple([ADDRESS.describe('staker: address')]);

// === Schema table ===

export const schemas = {
  '_stakerMap': _stakerMapSchema,
  'addToDeposit': addToDepositSchema,
  'amountStaked': amountStakedSchema,
  'anyTrustFastConfirmer': anyTrustFastConfirmerSchema,
  'baseStake': baseStakeSchema,
  'bridge': bridgeSchema,
  'chainId': chainIdSchema,
  'challengeGracePeriodBlocks': challengeGracePeriodBlocksSchema,
  'challengeManager': challengeManagerSchema,
  'computeAssertionHash': computeAssertionHashSchema,
  'confirmAssertion': confirmAssertionSchema,
  'confirmPeriodBlocks': confirmPeriodBlocksSchema,
  'fastConfirmAssertion': fastConfirmAssertionSchema,
  'fastConfirmNewAssertion': fastConfirmNewAssertionSchema,
  'forceConfirmAssertion': forceConfirmAssertionSchema,
  'forceCreateAssertion': forceCreateAssertionSchema,
  'forceRefundStaker': forceRefundStakerSchema,
  'genesisAssertionHash': genesisAssertionHashSchema,
  'getAssertion': getAssertionSchema,
  'getAssertionCreationBlockForLogLookup': getAssertionCreationBlockForLogLookupSchema,
  'getFirstChildCreationBlock': getFirstChildCreationBlockSchema,
  'getSecondChildCreationBlock': getSecondChildCreationBlockSchema,
  'getStaker': getStakerSchema,
  'getStakerAddress': getStakerAddressSchema,
  'getValidators': getValidatorsSchema,
  'inbox': inboxSchema,
  'isFirstChild': isFirstChildSchema,
  'isPending': isPendingSchema,
  'isStaked': isStakedSchema,
  'isValidator': isValidatorSchema,
  'latestConfirmed': latestConfirmedSchema,
  'latestStakedAssertion': latestStakedAssertionSchema,
  'loserStakeEscrow': loserStakeEscrowSchema,
  'minimumAssertionPeriod': minimumAssertionPeriodSchema,
  'newStake': newStakeSchema,
  'outbox': outboxSchema,
  'owner': ownerSchema,
  'pause': pauseSchema,
  'paused': pausedSchema,
  'proxiableUUID': proxiableUUIDSchema,
  'reduceDeposit': reduceDepositSchema,
  'removeOldOutbox': removeOldOutboxSchema,
  'removeWhitelistAfterFork': removeWhitelistAfterForkSchema,
  'removeWhitelistAfterValidatorAfk': removeWhitelistAfterValidatorAfkSchema,
  'resume': resumeSchema,
  'returnOldDeposit': returnOldDepositSchema,
  'returnOldDepositFor': returnOldDepositForSchema,
  'rollupDeploymentBlock': rollupDeploymentBlockSchema,
  'rollupEventInbox': rollupEventInboxSchema,
  'sequencerInbox': sequencerInboxSchema,
  'setAnyTrustFastConfirmer': setAnyTrustFastConfirmerSchema,
  'setBaseStake': setBaseStakeSchema,
  'setChallengeManager': setChallengeManagerSchema,
  'setConfirmPeriodBlocks': setConfirmPeriodBlocksSchema,
  'setDelayedInbox': setDelayedInboxSchema,
  'setInbox': setInboxSchema,
  'setLoserStakeEscrow': setLoserStakeEscrowSchema,
  'setMinimumAssertionPeriod': setMinimumAssertionPeriodSchema,
  'setOutbox': setOutboxSchema,
  'setOwner': setOwnerSchema,
  'setSequencerInbox': setSequencerInboxSchema,
  'setValidator': setValidatorSchema,
  'setValidatorAfkBlocks': setValidatorAfkBlocksSchema,
  'setValidatorWhitelistDisabled': setValidatorWhitelistDisabledSchema,
  'setWasmModuleRoot': setWasmModuleRootSchema,
  'stakeOnNewAssertion': stakeOnNewAssertionSchema,
  'stakeToken': stakeTokenSchema,
  'stakerCount': stakerCountSchema,
  'totalWithdrawableFunds': totalWithdrawableFundsSchema,
  'upgradeSecondaryTo': upgradeSecondaryToSchema,
  'upgradeSecondaryToAndCall': upgradeSecondaryToAndCallSchema,
  'upgradeTo': upgradeToSchema,
  'upgradeToAndCall': upgradeToAndCallSchema,
  'validateAssertionHash': validateAssertionHashSchema,
  'validateConfig': validateConfigSchema,
  'validatorAfkBlocks': validatorAfkBlocksSchema,
  'validatorWalletCreator': validatorWalletCreatorSchema,
  'validatorWhitelistDisabled': validatorWhitelistDisabledSchema,
  'wasmModuleRoot': wasmModuleRootSchema,
  'withdrawStakerFunds': withdrawStakerFundsSchema,
  'withdrawableFunds': withdrawableFundsSchema,
  'withdrawalAddress': withdrawalAddressSchema,
  '_stakerMap(address)': _stakerMapSchema,
  'addToDeposit(address,address,uint256)': addToDepositSchema,
  'amountStaked(address)': amountStakedSchema,
  'anyTrustFastConfirmer()': anyTrustFastConfirmerSchema,
  'baseStake()': baseStakeSchema,
  'bridge()': bridgeSchema,
  'chainId()': chainIdSchema,
  'challengeGracePeriodBlocks()': challengeGracePeriodBlocksSchema,
  'challengeManager()': challengeManagerSchema,
  'computeAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)':
    computeAssertionHashSchema,
  'confirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,(bytes32,uint256,address,uint64,uint64),bytes32)':
    confirmAssertionSchema,
  'confirmPeriodBlocks()': confirmPeriodBlocksSchema,
  'fastConfirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)':
    fastConfirmAssertionSchema,
  'fastConfirmNewAssertion(((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)':
    fastConfirmNewAssertionSchema,
  'forceConfirmAssertion(bytes32,bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32)':
    forceConfirmAssertionSchema,
  'forceCreateAssertion(bytes32,((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)':
    forceCreateAssertionSchema,
  'forceRefundStaker(address[])': forceRefundStakerSchema,
  'genesisAssertionHash()': genesisAssertionHashSchema,
  'getAssertion(bytes32)': getAssertionSchema,
  'getAssertionCreationBlockForLogLookup(bytes32)': getAssertionCreationBlockForLogLookupSchema,
  'getFirstChildCreationBlock(bytes32)': getFirstChildCreationBlockSchema,
  'getSecondChildCreationBlock(bytes32)': getSecondChildCreationBlockSchema,
  'getStaker(address)': getStakerSchema,
  'getStakerAddress(uint64)': getStakerAddressSchema,
  'getValidators()': getValidatorsSchema,
  'inbox()': inboxSchema,
  'initialize((uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64)),(address,address,address,address,address,address,address,address,address))':
    z.tuple([
      z
        .strictObject({
          confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
          stakeToken: ADDRESS.describe('stakeToken: address'),
          baseStake: UINT256.describe('baseStake: uint256'),
          wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
          owner: ADDRESS.describe('owner: address'),
          loserStakeEscrow: ADDRESS.describe('loserStakeEscrow: address'),
          chainId: UINT256.describe('chainId: uint256'),
          chainConfig: STRING.describe('chainConfig: string'),
          minimumAssertionPeriod: UINT256.describe('minimumAssertionPeriod: uint256'),
          validatorAfkBlocks: UINT64.describe('validatorAfkBlocks: uint64'),
          miniStakeValues: z.array(UINT256).describe('uint256[]'),
          sequencerInboxMaxTimeVariation: z
            .strictObject({
              delayBlocks: UINT256.describe('delayBlocks: uint256'),
              futureBlocks: UINT256.describe('futureBlocks: uint256'),
              delaySeconds: UINT256.describe('delaySeconds: uint256'),
              futureSeconds: UINT256.describe('futureSeconds: uint256'),
            })
            .describe('(uint256,uint256,uint256,uint256)'),
          layerZeroBlockEdgeHeight: UINT256.describe('layerZeroBlockEdgeHeight: uint256'),
          layerZeroBigStepEdgeHeight: UINT256.describe('layerZeroBigStepEdgeHeight: uint256'),
          layerZeroSmallStepEdgeHeight: UINT256.describe('layerZeroSmallStepEdgeHeight: uint256'),
          genesisAssertionState: z
            .strictObject({
              globalState: z
                .strictObject({
                  bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
                  u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
                })
                .describe('(bytes32[2],uint64[2])'),
              machineStatus: UINT8.describe('machineStatus: uint8'),
              endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
            })
            .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
          genesisInboxCount: UINT256.describe('genesisInboxCount: uint256'),
          anyTrustFastConfirmer: ADDRESS.describe('anyTrustFastConfirmer: address'),
          numBigStepLevel: UINT8.describe('numBigStepLevel: uint8'),
          challengeGracePeriodBlocks: UINT64.describe('challengeGracePeriodBlocks: uint64'),
          bufferConfig: z
            .strictObject({
              threshold: UINT64.describe('threshold: uint64'),
              max: UINT64.describe('max: uint64'),
              replenishRateInBasis: UINT64.describe('replenishRateInBasis: uint64'),
            })
            .describe('(uint64,uint64,uint64)'),
        })
        .describe(
          '(uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64))',
        ),
      z
        .strictObject({
          bridge: ADDRESS.describe('bridge: address'),
          sequencerInbox: ADDRESS.describe('sequencerInbox: address'),
          inbox: ADDRESS.describe('inbox: address'),
          outbox: ADDRESS.describe('outbox: address'),
          rollupEventInbox: ADDRESS.describe('rollupEventInbox: address'),
          challengeManager: ADDRESS.describe('challengeManager: address'),
          rollupAdminLogic: ADDRESS.describe('rollupAdminLogic: address'),
          rollupUserLogic: ADDRESS.describe('rollupUserLogic: address'),
          validatorWalletCreator: ADDRESS.describe('validatorWalletCreator: address'),
        })
        .describe('(address,address,address,address,address,address,address,address,address)'),
    ]),
  'initialize(address)': z.tuple([ADDRESS.describe('_stakeToken: address')]),
  'isFirstChild(bytes32)': isFirstChildSchema,
  'isPending(bytes32)': isPendingSchema,
  'isStaked(address)': isStakedSchema,
  'isValidator(address)': isValidatorSchema,
  'latestConfirmed()': latestConfirmedSchema,
  'latestStakedAssertion(address)': latestStakedAssertionSchema,
  'loserStakeEscrow()': loserStakeEscrowSchema,
  'minimumAssertionPeriod()': minimumAssertionPeriodSchema,
  'newStake(uint256,address)': newStakeSchema,
  'newStakeOnNewAssertion(uint256,((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)':
    z.tuple([
      UINT256.describe('tokenAmount: uint256'),
      z
        .strictObject({
          beforeStateData: z
            .strictObject({
              prevPrevAssertionHash: BYTES32.describe('prevPrevAssertionHash: bytes32'),
              sequencerBatchAcc: BYTES32.describe('sequencerBatchAcc: bytes32'),
              configData: z
                .strictObject({
                  wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
                  requiredStake: UINT256.describe('requiredStake: uint256'),
                  challengeManager: ADDRESS.describe('challengeManager: address'),
                  confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
                  nextInboxPosition: UINT64.describe('nextInboxPosition: uint64'),
                })
                .describe('(bytes32,uint256,address,uint64,uint64)'),
            })
            .describe('(bytes32,bytes32,(bytes32,uint256,address,uint64,uint64))'),
          beforeState: z
            .strictObject({
              globalState: z
                .strictObject({
                  bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
                  u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
                })
                .describe('(bytes32[2],uint64[2])'),
              machineStatus: UINT8.describe('machineStatus: uint8'),
              endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
            })
            .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
          afterState: z
            .strictObject({
              globalState: z
                .strictObject({
                  bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
                  u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
                })
                .describe('(bytes32[2],uint64[2])'),
              machineStatus: UINT8.describe('machineStatus: uint8'),
              endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
            })
            .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
        })
        .describe(
          '((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32))',
        ),
      BYTES32.describe('expectedAssertionHash: bytes32'),
    ]),
  'newStakeOnNewAssertion(uint256,((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32,address)':
    z.tuple([
      UINT256.describe('tokenAmount: uint256'),
      z
        .strictObject({
          beforeStateData: z
            .strictObject({
              prevPrevAssertionHash: BYTES32.describe('prevPrevAssertionHash: bytes32'),
              sequencerBatchAcc: BYTES32.describe('sequencerBatchAcc: bytes32'),
              configData: z
                .strictObject({
                  wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
                  requiredStake: UINT256.describe('requiredStake: uint256'),
                  challengeManager: ADDRESS.describe('challengeManager: address'),
                  confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
                  nextInboxPosition: UINT64.describe('nextInboxPosition: uint64'),
                })
                .describe('(bytes32,uint256,address,uint64,uint64)'),
            })
            .describe('(bytes32,bytes32,(bytes32,uint256,address,uint64,uint64))'),
          beforeState: z
            .strictObject({
              globalState: z
                .strictObject({
                  bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
                  u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
                })
                .describe('(bytes32[2],uint64[2])'),
              machineStatus: UINT8.describe('machineStatus: uint8'),
              endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
            })
            .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
          afterState: z
            .strictObject({
              globalState: z
                .strictObject({
                  bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
                  u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
                })
                .describe('(bytes32[2],uint64[2])'),
              machineStatus: UINT8.describe('machineStatus: uint8'),
              endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
            })
            .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
        })
        .describe(
          '((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32))',
        ),
      BYTES32.describe('expectedAssertionHash: bytes32'),
      ADDRESS.describe('_withdrawalAddress: address'),
    ]),
  'outbox()': outboxSchema,
  'owner()': ownerSchema,
  'pause()': pauseSchema,
  'paused()': pausedSchema,
  'proxiableUUID()': proxiableUUIDSchema,
  'reduceDeposit(uint256)': reduceDepositSchema,
  'removeOldOutbox(address)': removeOldOutboxSchema,
  'removeWhitelistAfterFork()': removeWhitelistAfterForkSchema,
  'removeWhitelistAfterValidatorAfk()': removeWhitelistAfterValidatorAfkSchema,
  'resume()': resumeSchema,
  'returnOldDeposit()': returnOldDepositSchema,
  'returnOldDepositFor(address)': returnOldDepositForSchema,
  'rollupDeploymentBlock()': rollupDeploymentBlockSchema,
  'rollupEventInbox()': rollupEventInboxSchema,
  'sequencerInbox()': sequencerInboxSchema,
  'setAnyTrustFastConfirmer(address)': setAnyTrustFastConfirmerSchema,
  'setBaseStake(uint256)': setBaseStakeSchema,
  'setChallengeManager(address)': setChallengeManagerSchema,
  'setConfirmPeriodBlocks(uint64)': setConfirmPeriodBlocksSchema,
  'setDelayedInbox(address,bool)': setDelayedInboxSchema,
  'setInbox(address)': setInboxSchema,
  'setLoserStakeEscrow(address)': setLoserStakeEscrowSchema,
  'setMinimumAssertionPeriod(uint256)': setMinimumAssertionPeriodSchema,
  'setOutbox(address)': setOutboxSchema,
  'setOwner(address)': setOwnerSchema,
  'setSequencerInbox(address)': setSequencerInboxSchema,
  'setValidator(address[],bool[])': setValidatorSchema,
  'setValidatorAfkBlocks(uint64)': setValidatorAfkBlocksSchema,
  'setValidatorWhitelistDisabled(bool)': setValidatorWhitelistDisabledSchema,
  'setWasmModuleRoot(bytes32)': setWasmModuleRootSchema,
  'stakeOnNewAssertion(((bytes32,bytes32,(bytes32,uint256,address,uint64,uint64)),((bytes32[2],uint64[2]),uint8,bytes32),((bytes32[2],uint64[2]),uint8,bytes32)),bytes32)':
    stakeOnNewAssertionSchema,
  'stakeToken()': stakeTokenSchema,
  'stakerCount()': stakerCountSchema,
  'totalWithdrawableFunds()': totalWithdrawableFundsSchema,
  'upgradeSecondaryTo(address)': upgradeSecondaryToSchema,
  'upgradeSecondaryToAndCall(address,bytes)': upgradeSecondaryToAndCallSchema,
  'upgradeTo(address)': upgradeToSchema,
  'upgradeToAndCall(address,bytes)': upgradeToAndCallSchema,
  'validateAssertionHash(bytes32,((bytes32[2],uint64[2]),uint8,bytes32),bytes32,bytes32)':
    validateAssertionHashSchema,
  'validateConfig(bytes32,(bytes32,uint256,address,uint64,uint64))': validateConfigSchema,
  'validatorAfkBlocks()': validatorAfkBlocksSchema,
  'validatorWalletCreator()': validatorWalletCreatorSchema,
  'validatorWhitelistDisabled()': validatorWhitelistDisabledSchema,
  'wasmModuleRoot()': wasmModuleRootSchema,
  'withdrawStakerFunds()': withdrawStakerFundsSchema,
  'withdrawableFunds(address)': withdrawableFundsSchema,
  'withdrawalAddress(address)': withdrawalAddressSchema,
} as const;
