// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES32 = z
  .string()
  .regex(/^0x[0-9a-fA-F]{64}$/)
  .transform((v) => v as `0x${string}`);
const STRING = z.string();
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 64n) - 1n);

// === Function schemas ===

// bridgeCreator()
export const bridgeCreatorSchema = z.tuple([]);

// challengeManagerTemplate()
export const challengeManagerTemplateSchema = z.tuple([]);

// createRollup(((uint64,uint64,address,uint256,bytes32,address,address,uint256,string,uint64,(uint256,uint256,uint256,uint256)),address,address[],uint256,address,bool,uint256))
export const createRollupSchema = z.tuple([
  z
    .strictObject({
      config: z
        .strictObject({
          confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
          extraChallengeTimeBlocks: UINT64.describe('extraChallengeTimeBlocks: uint64'),
          stakeToken: ADDRESS.describe('stakeToken: address'),
          baseStake: UINT256.describe('baseStake: uint256'),
          wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
          owner: ADDRESS.describe('owner: address'),
          loserStakeEscrow: ADDRESS.describe('loserStakeEscrow: address'),
          chainId: UINT256.describe('chainId: uint256'),
          chainConfig: STRING.describe('chainConfig: string'),
          genesisBlockNum: UINT64.describe('genesisBlockNum: uint64'),
          sequencerInboxMaxTimeVariation: z
            .strictObject({
              delayBlocks: UINT256.describe('delayBlocks: uint256'),
              futureBlocks: UINT256.describe('futureBlocks: uint256'),
              delaySeconds: UINT256.describe('delaySeconds: uint256'),
              futureSeconds: UINT256.describe('futureSeconds: uint256'),
            })
            .describe('(uint256,uint256,uint256,uint256)'),
        })
        .describe(
          '(uint64,uint64,address,uint256,bytes32,address,address,uint256,string,uint64,(uint256,uint256,uint256,uint256))',
        ),
      batchPoster: ADDRESS.describe('batchPoster: address'),
      validators: z.array(ADDRESS).describe('address[]'),
      maxDataSize: UINT256.describe('maxDataSize: uint256'),
      nativeToken: ADDRESS.describe('nativeToken: address'),
      deployFactoriesToL2: BOOL.describe('deployFactoriesToL2: bool'),
      maxFeePerGasForRetryables: UINT256.describe('maxFeePerGasForRetryables: uint256'),
    })
    .describe(
      '((uint64,uint64,address,uint256,bytes32,address,address,uint256,string,uint64,(uint256,uint256,uint256,uint256)),address,address[],uint256,address,bool,uint256)',
    ),
]);

// l2FactoriesDeployer()
export const l2FactoriesDeployerSchema = z.tuple([]);

// osp()
export const ospSchema = z.tuple([]);

// owner()
export const ownerSchema = z.tuple([]);

// renounceOwnership()
export const renounceOwnershipSchema = z.tuple([]);

// rollupAdminLogic()
export const rollupAdminLogicSchema = z.tuple([]);

// rollupUserLogic()
export const rollupUserLogicSchema = z.tuple([]);

// setTemplates(address,address,address,address,address,address,address,address,address)
export const setTemplatesSchema = z.tuple([
  ADDRESS.describe('_bridgeCreator: address'),
  ADDRESS.describe('_osp: address'),
  ADDRESS.describe('_challengeManagerLogic: address'),
  ADDRESS.describe('_rollupAdminLogic: address'),
  ADDRESS.describe('_rollupUserLogic: address'),
  ADDRESS.describe('_upgradeExecutorLogic: address'),
  ADDRESS.describe('_validatorUtils: address'),
  ADDRESS.describe('_validatorWalletCreator: address'),
  ADDRESS.describe('_l2FactoriesDeployer: address'),
]);

// transferOwnership(address)
export const transferOwnershipSchema = z.tuple([ADDRESS.describe('newOwner: address')]);

// upgradeExecutorLogic()
export const upgradeExecutorLogicSchema = z.tuple([]);

// validatorUtils()
export const validatorUtilsSchema = z.tuple([]);

// validatorWalletCreator()
export const validatorWalletCreatorSchema = z.tuple([]);

// === Schema table ===

export const schemas = {
  'bridgeCreator': bridgeCreatorSchema,
  'challengeManagerTemplate': challengeManagerTemplateSchema,
  'createRollup': createRollupSchema,
  'l2FactoriesDeployer': l2FactoriesDeployerSchema,
  'osp': ospSchema,
  'owner': ownerSchema,
  'renounceOwnership': renounceOwnershipSchema,
  'rollupAdminLogic': rollupAdminLogicSchema,
  'rollupUserLogic': rollupUserLogicSchema,
  'setTemplates': setTemplatesSchema,
  'transferOwnership': transferOwnershipSchema,
  'upgradeExecutorLogic': upgradeExecutorLogicSchema,
  'validatorUtils': validatorUtilsSchema,
  'validatorWalletCreator': validatorWalletCreatorSchema,
  'bridgeCreator()': bridgeCreatorSchema,
  'challengeManagerTemplate()': challengeManagerTemplateSchema,
  'createRollup(((uint64,uint64,address,uint256,bytes32,address,address,uint256,string,uint64,(uint256,uint256,uint256,uint256)),address,address[],uint256,address,bool,uint256))':
    createRollupSchema,
  'l2FactoriesDeployer()': l2FactoriesDeployerSchema,
  'osp()': ospSchema,
  'owner()': ownerSchema,
  'renounceOwnership()': renounceOwnershipSchema,
  'rollupAdminLogic()': rollupAdminLogicSchema,
  'rollupUserLogic()': rollupUserLogicSchema,
  'setTemplates(address,address,address,address,address,address,address,address,address)':
    setTemplatesSchema,
  'transferOwnership(address)': transferOwnershipSchema,
  'upgradeExecutorLogic()': upgradeExecutorLogicSchema,
  'validatorUtils()': validatorUtilsSchema,
  'validatorWalletCreator()': validatorWalletCreatorSchema,
} as const;
