// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES32 = z
  .string()
  .regex(/^0x[0-9a-fA-F]{64}$/)
  .transform((v) => v as `0x${string}`);
const STRING = z.string();
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 8n) - 1n)
  .transform((b) => Number(b));

// === Function schemas ===

// bridgeCreator()
export const bridgeCreatorSchema = z.tuple([]);

// challengeManagerTemplate()
export const challengeManagerTemplateSchema = z.tuple([]);

// createRollup(((uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64)),address[],uint256,address,bool,uint256,address[],address,address))
export const createRollupSchema = z.tuple([
  z
    .strictObject({
      config: z
        .strictObject({
          confirmPeriodBlocks: UINT64.describe('confirmPeriodBlocks: uint64'),
          stakeToken: ADDRESS.describe('stakeToken: address'),
          baseStake: UINT256.describe('baseStake: uint256'),
          wasmModuleRoot: BYTES32.describe('wasmModuleRoot: bytes32'),
          owner: ADDRESS.describe('owner: address'),
          loserStakeEscrow: ADDRESS.describe('loserStakeEscrow: address'),
          chainId: UINT256.describe('chainId: uint256'),
          chainConfig: STRING.describe('chainConfig: string'),
          minimumAssertionPeriod: UINT256.describe('minimumAssertionPeriod: uint256'),
          validatorAfkBlocks: UINT64.describe('validatorAfkBlocks: uint64'),
          miniStakeValues: z.array(UINT256).describe('uint256[]'),
          sequencerInboxMaxTimeVariation: z
            .strictObject({
              delayBlocks: UINT256.describe('delayBlocks: uint256'),
              futureBlocks: UINT256.describe('futureBlocks: uint256'),
              delaySeconds: UINT256.describe('delaySeconds: uint256'),
              futureSeconds: UINT256.describe('futureSeconds: uint256'),
            })
            .describe('(uint256,uint256,uint256,uint256)'),
          layerZeroBlockEdgeHeight: UINT256.describe('layerZeroBlockEdgeHeight: uint256'),
          layerZeroBigStepEdgeHeight: UINT256.describe('layerZeroBigStepEdgeHeight: uint256'),
          layerZeroSmallStepEdgeHeight: UINT256.describe('layerZeroSmallStepEdgeHeight: uint256'),
          genesisAssertionState: z
            .strictObject({
              globalState: z
                .strictObject({
                  bytes32Vals: z.array(BYTES32).length(2).describe('bytes32[2]'),
                  u64Vals: z.array(UINT64).length(2).describe('uint64[2]'),
                })
                .describe('(bytes32[2],uint64[2])'),
              machineStatus: UINT8.describe('machineStatus: uint8'),
              endHistoryRoot: BYTES32.describe('endHistoryRoot: bytes32'),
            })
            .describe('((bytes32[2],uint64[2]),uint8,bytes32)'),
          genesisInboxCount: UINT256.describe('genesisInboxCount: uint256'),
          anyTrustFastConfirmer: ADDRESS.describe('anyTrustFastConfirmer: address'),
          numBigStepLevel: UINT8.describe('numBigStepLevel: uint8'),
          challengeGracePeriodBlocks: UINT64.describe('challengeGracePeriodBlocks: uint64'),
          bufferConfig: z
            .strictObject({
              threshold: UINT64.describe('threshold: uint64'),
              max: UINT64.describe('max: uint64'),
              replenishRateInBasis: UINT64.describe('replenishRateInBasis: uint64'),
            })
            .describe('(uint64,uint64,uint64)'),
        })
        .describe(
          '(uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64))',
        ),
      validators: z.array(ADDRESS).describe('address[]'),
      maxDataSize: UINT256.describe('maxDataSize: uint256'),
      nativeToken: ADDRESS.describe('nativeToken: address'),
      deployFactoriesToL2: BOOL.describe('deployFactoriesToL2: bool'),
      maxFeePerGasForRetryables: UINT256.describe('maxFeePerGasForRetryables: uint256'),
      batchPosters: z.array(ADDRESS).describe('address[]'),
      batchPosterManager: ADDRESS.describe('batchPosterManager: address'),
      feeTokenPricer: ADDRESS.describe('feeTokenPricer: address'),
    })
    .describe(
      '((uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64)),address[],uint256,address,bool,uint256,address[],address,address)',
    ),
]);

// l2FactoriesDeployer()
export const l2FactoriesDeployerSchema = z.tuple([]);

// osp()
export const ospSchema = z.tuple([]);

// owner()
export const ownerSchema = z.tuple([]);

// renounceOwnership()
export const renounceOwnershipSchema = z.tuple([]);

// rollupAdminLogic()
export const rollupAdminLogicSchema = z.tuple([]);

// rollupUserLogic()
export const rollupUserLogicSchema = z.tuple([]);

// setTemplates(address,address,address,address,address,address,address,address)
export const setTemplatesSchema = z.tuple([
  ADDRESS.describe('_bridgeCreator: address'),
  ADDRESS.describe('_osp: address'),
  ADDRESS.describe('_challengeManagerLogic: address'),
  ADDRESS.describe('_rollupAdminLogic: address'),
  ADDRESS.describe('_rollupUserLogic: address'),
  ADDRESS.describe('_upgradeExecutorLogic: address'),
  ADDRESS.describe('_validatorWalletCreator: address'),
  ADDRESS.describe('_l2FactoriesDeployer: address'),
]);

// transferOwnership(address)
export const transferOwnershipSchema = z.tuple([ADDRESS.describe('newOwner: address')]);

// upgradeExecutorLogic()
export const upgradeExecutorLogicSchema = z.tuple([]);

// validatorWalletCreator()
export const validatorWalletCreatorSchema = z.tuple([]);

// === Schema table ===

export const schemas = {
  'bridgeCreator': bridgeCreatorSchema,
  'challengeManagerTemplate': challengeManagerTemplateSchema,
  'createRollup': createRollupSchema,
  'l2FactoriesDeployer': l2FactoriesDeployerSchema,
  'osp': ospSchema,
  'owner': ownerSchema,
  'renounceOwnership': renounceOwnershipSchema,
  'rollupAdminLogic': rollupAdminLogicSchema,
  'rollupUserLogic': rollupUserLogicSchema,
  'setTemplates': setTemplatesSchema,
  'transferOwnership': transferOwnershipSchema,
  'upgradeExecutorLogic': upgradeExecutorLogicSchema,
  'validatorWalletCreator': validatorWalletCreatorSchema,
  'bridgeCreator()': bridgeCreatorSchema,
  'challengeManagerTemplate()': challengeManagerTemplateSchema,
  'createRollup(((uint64,address,uint256,bytes32,address,address,uint256,string,uint256,uint64,uint256[],(uint256,uint256,uint256,uint256),uint256,uint256,uint256,((bytes32[2],uint64[2]),uint8,bytes32),uint256,address,uint8,uint64,(uint64,uint64,uint64)),address[],uint256,address,bool,uint256,address[],address,address))':
    createRollupSchema,
  'l2FactoriesDeployer()': l2FactoriesDeployerSchema,
  'osp()': ospSchema,
  'owner()': ownerSchema,
  'renounceOwnership()': renounceOwnershipSchema,
  'rollupAdminLogic()': rollupAdminLogicSchema,
  'rollupUserLogic()': rollupUserLogicSchema,
  'setTemplates(address,address,address,address,address,address,address,address)':
    setTemplatesSchema,
  'transferOwnership(address)': transferOwnershipSchema,
  'upgradeExecutorLogic()': upgradeExecutorLogicSchema,
  'validatorWalletCreator()': validatorWalletCreatorSchema,
} as const;
