// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z
  .string()
  .regex(/^0x([0-9a-fA-F]{2})*$/)
  .transform((v) => v as `0x${string}`);
const BYTES32 = z
  .string()
  .regex(/^0x[0-9a-fA-F]{64}$/)
  .transform((v) => v as `0x${string}`);
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 8n) - 1n)
  .transform((b) => Number(b));

// === Function schemas ===

// BROTLI_MESSAGE_HEADER_FLAG()
export const BROTLI_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// DAS_MESSAGE_HEADER_FLAG()
export const DAS_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// DATA_AUTHENTICATED_FLAG()
export const DATA_AUTHENTICATED_FLAGSchema = z.tuple([]);

// DATA_BLOB_HEADER_FLAG()
export const DATA_BLOB_HEADER_FLAGSchema = z.tuple([]);

// HEADER_LENGTH()
export const HEADER_LENGTHSchema = z.tuple([]);

// TREE_DAS_MESSAGE_HEADER_FLAG()
export const TREE_DAS_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// ZERO_HEAVY_MESSAGE_HEADER_FLAG()
export const ZERO_HEAVY_MESSAGE_HEADER_FLAGSchema = z.tuple([]);

// addSequencerL2Batch(uint256,bytes,uint256,address,uint256,uint256)
export const addSequencerL2BatchSchema = z.tuple([
  UINT256.describe('sequenceNumber: uint256'),
  BYTES.describe('data: bytes'),
  UINT256.describe('afterDelayedMessagesRead: uint256'),
  ADDRESS.describe('gasRefunder: address'),
  UINT256.describe('prevMessageCount: uint256'),
  UINT256.describe('newMessageCount: uint256'),
]);

// addSequencerL2BatchFromBlobs(uint256,uint256,address,uint256,uint256)
export const addSequencerL2BatchFromBlobsSchema = z.tuple([
  UINT256.describe('sequenceNumber: uint256'),
  UINT256.describe('afterDelayedMessagesRead: uint256'),
  ADDRESS.describe('gasRefunder: address'),
  UINT256.describe('prevMessageCount: uint256'),
  UINT256.describe('newMessageCount: uint256'),
]);

// batchCount()
export const batchCountSchema = z.tuple([]);

// batchPosterManager()
export const batchPosterManagerSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// dasKeySetInfo(bytes32)
export const dasKeySetInfoSchema = z.tuple([BYTES32]);

// forceInclusion(uint256,uint8,uint64[2],uint256,address,bytes32)
export const forceInclusionSchema = z.tuple([
  UINT256.describe('_totalDelayedMessagesRead: uint256'),
  UINT8.describe('kind: uint8'),
  z.array(UINT64).length(2).describe('uint64[2]'),
  UINT256.describe('baseFeeL1: uint256'),
  ADDRESS.describe('sender: address'),
  BYTES32.describe('messageDataHash: bytes32'),
]);

// getKeysetCreationBlock(bytes32)
export const getKeysetCreationBlockSchema = z.tuple([BYTES32.describe('ksHash: bytes32')]);

// inboxAccs(uint256)
export const inboxAccsSchema = z.tuple([UINT256.describe('index: uint256')]);

// initialize(address,(uint256,uint256,uint256,uint256))
export const initializeSchema = z.tuple([
  ADDRESS.describe('bridge_: address'),
  z
    .strictObject({
      delayBlocks: UINT256.describe('delayBlocks: uint256'),
      futureBlocks: UINT256.describe('futureBlocks: uint256'),
      delaySeconds: UINT256.describe('delaySeconds: uint256'),
      futureSeconds: UINT256.describe('futureSeconds: uint256'),
    })
    .describe('(uint256,uint256,uint256,uint256)'),
]);

// invalidateKeysetHash(bytes32)
export const invalidateKeysetHashSchema = z.tuple([BYTES32.describe('ksHash: bytes32')]);

// isBatchPoster(address)
export const isBatchPosterSchema = z.tuple([ADDRESS]);

// isSequencer(address)
export const isSequencerSchema = z.tuple([ADDRESS]);

// isUsingFeeToken()
export const isUsingFeeTokenSchema = z.tuple([]);

// isValidKeysetHash(bytes32)
export const isValidKeysetHashSchema = z.tuple([BYTES32.describe('ksHash: bytes32')]);

// maxDataSize()
export const maxDataSizeSchema = z.tuple([]);

// maxTimeVariation()
export const maxTimeVariationSchema = z.tuple([]);

// postUpgradeInit()
export const postUpgradeInitSchema = z.tuple([]);

// reader4844()
export const reader4844Schema = z.tuple([]);

// removeDelayAfterFork()
export const removeDelayAfterForkSchema = z.tuple([]);

// rollup()
export const rollupSchema = z.tuple([]);

// setBatchPosterManager(address)
export const setBatchPosterManagerSchema = z.tuple([
  ADDRESS.describe('newBatchPosterManager: address'),
]);

// setIsBatchPoster(address,bool)
export const setIsBatchPosterSchema = z.tuple([
  ADDRESS.describe('addr: address'),
  BOOL.describe('isBatchPoster_: bool'),
]);

// setIsSequencer(address,bool)
export const setIsSequencerSchema = z.tuple([
  ADDRESS.describe('addr: address'),
  BOOL.describe('isSequencer_: bool'),
]);

// setMaxTimeVariation((uint256,uint256,uint256,uint256))
export const setMaxTimeVariationSchema = z.tuple([
  z
    .strictObject({
      delayBlocks: UINT256.describe('delayBlocks: uint256'),
      futureBlocks: UINT256.describe('futureBlocks: uint256'),
      delaySeconds: UINT256.describe('delaySeconds: uint256'),
      futureSeconds: UINT256.describe('futureSeconds: uint256'),
    })
    .describe('(uint256,uint256,uint256,uint256)'),
]);

// setValidKeyset(bytes)
export const setValidKeysetSchema = z.tuple([BYTES.describe('keysetBytes: bytes')]);

// totalDelayedMessagesRead()
export const totalDelayedMessagesReadSchema = z.tuple([]);

// updateRollupAddress()
export const updateRollupAddressSchema = z.tuple([]);

// === Schema table ===

export const schemas = {
  'BROTLI_MESSAGE_HEADER_FLAG': BROTLI_MESSAGE_HEADER_FLAGSchema,
  'DAS_MESSAGE_HEADER_FLAG': DAS_MESSAGE_HEADER_FLAGSchema,
  'DATA_AUTHENTICATED_FLAG': DATA_AUTHENTICATED_FLAGSchema,
  'DATA_BLOB_HEADER_FLAG': DATA_BLOB_HEADER_FLAGSchema,
  'HEADER_LENGTH': HEADER_LENGTHSchema,
  'TREE_DAS_MESSAGE_HEADER_FLAG': TREE_DAS_MESSAGE_HEADER_FLAGSchema,
  'ZERO_HEAVY_MESSAGE_HEADER_FLAG': ZERO_HEAVY_MESSAGE_HEADER_FLAGSchema,
  'addSequencerL2Batch': addSequencerL2BatchSchema,
  'addSequencerL2BatchFromBlobs': addSequencerL2BatchFromBlobsSchema,
  'batchCount': batchCountSchema,
  'batchPosterManager': batchPosterManagerSchema,
  'bridge': bridgeSchema,
  'dasKeySetInfo': dasKeySetInfoSchema,
  'forceInclusion': forceInclusionSchema,
  'getKeysetCreationBlock': getKeysetCreationBlockSchema,
  'inboxAccs': inboxAccsSchema,
  'initialize': initializeSchema,
  'invalidateKeysetHash': invalidateKeysetHashSchema,
  'isBatchPoster': isBatchPosterSchema,
  'isSequencer': isSequencerSchema,
  'isUsingFeeToken': isUsingFeeTokenSchema,
  'isValidKeysetHash': isValidKeysetHashSchema,
  'maxDataSize': maxDataSizeSchema,
  'maxTimeVariation': maxTimeVariationSchema,
  'postUpgradeInit': postUpgradeInitSchema,
  'reader4844': reader4844Schema,
  'removeDelayAfterFork': removeDelayAfterForkSchema,
  'rollup': rollupSchema,
  'setBatchPosterManager': setBatchPosterManagerSchema,
  'setIsBatchPoster': setIsBatchPosterSchema,
  'setIsSequencer': setIsSequencerSchema,
  'setMaxTimeVariation': setMaxTimeVariationSchema,
  'setValidKeyset': setValidKeysetSchema,
  'totalDelayedMessagesRead': totalDelayedMessagesReadSchema,
  'updateRollupAddress': updateRollupAddressSchema,
  'BROTLI_MESSAGE_HEADER_FLAG()': BROTLI_MESSAGE_HEADER_FLAGSchema,
  'DAS_MESSAGE_HEADER_FLAG()': DAS_MESSAGE_HEADER_FLAGSchema,
  'DATA_AUTHENTICATED_FLAG()': DATA_AUTHENTICATED_FLAGSchema,
  'DATA_BLOB_HEADER_FLAG()': DATA_BLOB_HEADER_FLAGSchema,
  'HEADER_LENGTH()': HEADER_LENGTHSchema,
  'TREE_DAS_MESSAGE_HEADER_FLAG()': TREE_DAS_MESSAGE_HEADER_FLAGSchema,
  'ZERO_HEAVY_MESSAGE_HEADER_FLAG()': ZERO_HEAVY_MESSAGE_HEADER_FLAGSchema,
  'addSequencerL2Batch(uint256,bytes,uint256,address,uint256,uint256)': addSequencerL2BatchSchema,
  'addSequencerL2BatchFromBlobs(uint256,uint256,address,uint256,uint256)':
    addSequencerL2BatchFromBlobsSchema,
  'addSequencerL2BatchFromOrigin(uint256,bytes,uint256,address)': z.tuple([
    UINT256,
    BYTES,
    UINT256,
    ADDRESS,
  ]),
  'addSequencerL2BatchFromOrigin(uint256,bytes,uint256,address,uint256,uint256)': z.tuple([
    UINT256.describe('sequenceNumber: uint256'),
    BYTES.describe('data: bytes'),
    UINT256.describe('afterDelayedMessagesRead: uint256'),
    ADDRESS.describe('gasRefunder: address'),
    UINT256.describe('prevMessageCount: uint256'),
    UINT256.describe('newMessageCount: uint256'),
  ]),
  'batchCount()': batchCountSchema,
  'batchPosterManager()': batchPosterManagerSchema,
  'bridge()': bridgeSchema,
  'dasKeySetInfo(bytes32)': dasKeySetInfoSchema,
  'forceInclusion(uint256,uint8,uint64[2],uint256,address,bytes32)': forceInclusionSchema,
  'getKeysetCreationBlock(bytes32)': getKeysetCreationBlockSchema,
  'inboxAccs(uint256)': inboxAccsSchema,
  'initialize(address,(uint256,uint256,uint256,uint256))': initializeSchema,
  'invalidateKeysetHash(bytes32)': invalidateKeysetHashSchema,
  'isBatchPoster(address)': isBatchPosterSchema,
  'isSequencer(address)': isSequencerSchema,
  'isUsingFeeToken()': isUsingFeeTokenSchema,
  'isValidKeysetHash(bytes32)': isValidKeysetHashSchema,
  'maxDataSize()': maxDataSizeSchema,
  'maxTimeVariation()': maxTimeVariationSchema,
  'postUpgradeInit()': postUpgradeInitSchema,
  'reader4844()': reader4844Schema,
  'removeDelayAfterFork()': removeDelayAfterForkSchema,
  'rollup()': rollupSchema,
  'setBatchPosterManager(address)': setBatchPosterManagerSchema,
  'setIsBatchPoster(address,bool)': setIsBatchPosterSchema,
  'setIsSequencer(address,bool)': setIsSequencerSchema,
  'setMaxTimeVariation((uint256,uint256,uint256,uint256))': setMaxTimeVariationSchema,
  'setValidKeyset(bytes)': setValidKeysetSchema,
  'totalDelayedMessagesRead()': totalDelayedMessagesReadSchema,
  'updateRollupAddress()': updateRollupAddressSchema,
} as const;
