//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
// Inbox
//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

export const inboxABI = [
  {
    stateMutability: 'nonpayable',
    type: 'constructor',
    inputs: [{ name: '_maxDataSize', internalType: 'uint256', type: 'uint256' }],
  },
  {
    type: 'error',
    inputs: [
      { name: 'dataLength', internalType: 'uint256', type: 'uint256' },
      { name: 'maxDataLength', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'DataTooLarge',
  },
  { type: 'error', inputs: [], name: 'GasLimitTooLarge' },
  {
    type: 'error',
    inputs: [
      { name: 'expected', internalType: 'uint256', type: 'uint256' },
      { name: 'actual', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'InsufficientSubmissionCost',
  },
  {
    type: 'error',
    inputs: [
      { name: 'expected', internalType: 'uint256', type: 'uint256' },
      { name: 'actual', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'InsufficientValue',
  },
  { type: 'error', inputs: [], name: 'L1Forked' },
  {
    type: 'error',
    inputs: [{ name: 'origin', internalType: 'address', type: 'address' }],
    name: 'NotAllowedOrigin',
  },
  { type: 'error', inputs: [], name: 'NotCodelessOrigin' },
  { type: 'error', inputs: [], name: 'NotForked' },
  { type: 'error', inputs: [], name: 'NotOrigin' },
  {
    type: 'error',
    inputs: [
      { name: 'sender', internalType: 'address', type: 'address' },
      { name: 'owner', internalType: 'address', type: 'address' },
    ],
    name: 'NotOwner',
  },
  {
    type: 'error',
    inputs: [
      { name: 'sender', internalType: 'address', type: 'address' },
      { name: 'rollup', internalType: 'address', type: 'address' },
      { name: 'owner', internalType: 'address', type: 'address' },
    ],
    name: 'NotRollupOrOwner',
  },
  {
    type: 'error',
    inputs: [
      { name: 'from', internalType: 'address', type: 'address' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'l2CallValue', internalType: 'uint256', type: 'uint256' },
      { name: 'deposit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxSubmissionCost', internalType: 'uint256', type: 'uint256' },
      { name: 'excessFeeRefundAddress', internalType: 'address', type: 'address' },
      { name: 'callValueRefundAddress', internalType: 'address', type: 'address' },
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'RetryableData',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'user', internalType: 'address', type: 'address', indexed: true },
      { name: 'val', internalType: 'bool', type: 'bool', indexed: false },
    ],
    name: 'AllowListAddressSet',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'isEnabled', internalType: 'bool', type: 'bool', indexed: false }],
    name: 'AllowListEnabledUpdated',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [
      { name: 'messageNum', internalType: 'uint256', type: 'uint256', indexed: true },
      { name: 'data', internalType: 'bytes', type: 'bytes', indexed: false },
    ],
    name: 'InboxMessageDelivered',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'messageNum', internalType: 'uint256', type: 'uint256', indexed: true }],
    name: 'InboxMessageDeliveredFromOrigin',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'version', internalType: 'uint8', type: 'uint8', indexed: false }],
    name: 'Initialized',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: false }],
    name: 'Paused',
  },
  {
    type: 'event',
    anonymous: false,
    inputs: [{ name: 'account', internalType: 'address', type: 'address', indexed: false }],
    name: 'Unpaused',
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'allowListEnabled',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'bridge',
    outputs: [{ name: '', internalType: 'contract IBridge', type: 'address' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [
      { name: 'dataLength', internalType: 'uint256', type: 'uint256' },
      { name: 'baseFee', internalType: 'uint256', type: 'uint256' },
    ],
    name: 'calculateRetryableSubmissionFee',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'l2CallValue', internalType: 'uint256', type: 'uint256' },
      { name: 'maxSubmissionCost', internalType: 'uint256', type: 'uint256' },
      { name: 'excessFeeRefundAddress', internalType: 'address', type: 'address' },
      { name: 'callValueRefundAddress', internalType: 'address', type: 'address' },
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'createRetryableTicket',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'l2CallValue', internalType: 'uint256', type: 'uint256' },
      { name: 'maxSubmissionCost', internalType: 'uint256', type: 'uint256' },
      { name: 'excessFeeRefundAddress', internalType: 'address', type: 'address' },
      { name: 'callValueRefundAddress', internalType: 'address', type: 'address' },
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'createRetryableTicketNoRefundAliasRewrite',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
    name: 'depositEth',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [],
    name: 'depositEth',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'getProxyAdmin',
    outputs: [{ name: '', internalType: 'address', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: '_bridge', internalType: 'contract IBridge', type: 'address' },
      { name: '_sequencerInbox', internalType: 'contract ISequencerInbox', type: 'address' },
    ],
    name: 'initialize',
    outputs: [],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [{ name: '', internalType: 'address', type: 'address' }],
    name: 'isAllowed',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'maxDataSize',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'pause', outputs: [] },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'paused',
    outputs: [{ name: '', internalType: 'bool', type: 'bool' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '', internalType: 'contract IBridge', type: 'address' }],
    name: 'postUpgradeInit',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'sendContractTransaction',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'sendL1FundedContractTransaction',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'nonce', internalType: 'uint256', type: 'uint256' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'sendL1FundedUnsignedTransaction',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'nonce', internalType: 'uint256', type: 'uint256' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'sendL1FundedUnsignedTransactionToFork',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'messageData', internalType: 'bytes', type: 'bytes' }],
    name: 'sendL2Message',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: 'messageData', internalType: 'bytes', type: 'bytes' }],
    name: 'sendL2MessageFromOrigin',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'nonce', internalType: 'uint256', type: 'uint256' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'sendUnsignedTransaction',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'nonce', internalType: 'uint256', type: 'uint256' },
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'sendUnsignedTransactionToFork',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'nonce', internalType: 'uint256', type: 'uint256' },
      { name: 'value', internalType: 'uint256', type: 'uint256' },
      { name: 'withdrawTo', internalType: 'address', type: 'address' },
    ],
    name: 'sendWithdrawEthToFork',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
  {
    stateMutability: 'view',
    type: 'function',
    inputs: [],
    name: 'sequencerInbox',
    outputs: [{ name: '', internalType: 'contract ISequencerInbox', type: 'address' }],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [
      { name: 'user', internalType: 'address[]', type: 'address[]' },
      { name: 'val', internalType: 'bool[]', type: 'bool[]' },
    ],
    name: 'setAllowList',
    outputs: [],
  },
  {
    stateMutability: 'nonpayable',
    type: 'function',
    inputs: [{ name: '_allowListEnabled', internalType: 'bool', type: 'bool' }],
    name: 'setAllowListEnabled',
    outputs: [],
  },
  { stateMutability: 'nonpayable', type: 'function', inputs: [], name: 'unpause', outputs: [] },
  {
    stateMutability: 'payable',
    type: 'function',
    inputs: [
      { name: 'to', internalType: 'address', type: 'address' },
      { name: 'l2CallValue', internalType: 'uint256', type: 'uint256' },
      { name: 'maxSubmissionCost', internalType: 'uint256', type: 'uint256' },
      { name: 'excessFeeRefundAddress', internalType: 'address', type: 'address' },
      { name: 'callValueRefundAddress', internalType: 'address', type: 'address' },
      { name: 'gasLimit', internalType: 'uint256', type: 'uint256' },
      { name: 'maxFeePerGas', internalType: 'uint256', type: 'uint256' },
      { name: 'data', internalType: 'bytes', type: 'bytes' },
    ],
    name: 'unsafeCreateRetryableTicket',
    outputs: [{ name: '', internalType: 'uint256', type: 'uint256' }],
  },
] as const;
