// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const BOOL = z.boolean();
const BYTES = z
  .string()
  .regex(/^0x([0-9a-fA-F]{2})*$/)
  .transform((v) => v as `0x${string}`);
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// allowListEnabled()
export const allowListEnabledSchema = z.tuple([]);

// bridge()
export const bridgeSchema = z.tuple([]);

// calculateRetryableSubmissionFee(uint256,uint256)
export const calculateRetryableSubmissionFeeSchema = z.tuple([
  UINT256.describe('dataLength: uint256'),
  UINT256.describe('baseFee: uint256'),
]);

// createRetryableTicket(address,uint256,uint256,address,address,uint256,uint256,bytes)
export const createRetryableTicketSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('l2CallValue: uint256'),
  UINT256.describe('maxSubmissionCost: uint256'),
  ADDRESS.describe('excessFeeRefundAddress: address'),
  ADDRESS.describe('callValueRefundAddress: address'),
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  BYTES.describe('data: bytes'),
]);

// createRetryableTicketNoRefundAliasRewrite(address,uint256,uint256,address,address,uint256,uint256,bytes)
export const createRetryableTicketNoRefundAliasRewriteSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('l2CallValue: uint256'),
  UINT256.describe('maxSubmissionCost: uint256'),
  ADDRESS.describe('excessFeeRefundAddress: address'),
  ADDRESS.describe('callValueRefundAddress: address'),
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  BYTES.describe('data: bytes'),
]);

// getProxyAdmin()
export const getProxyAdminSchema = z.tuple([]);

// initialize(address,address)
export const initializeSchema = z.tuple([
  ADDRESS.describe('_bridge: address'),
  ADDRESS.describe('_sequencerInbox: address'),
]);

// isAllowed(address)
export const isAllowedSchema = z.tuple([ADDRESS]);

// maxDataSize()
export const maxDataSizeSchema = z.tuple([]);

// pause()
export const pauseSchema = z.tuple([]);

// paused()
export const pausedSchema = z.tuple([]);

// postUpgradeInit(address)
export const postUpgradeInitSchema = z.tuple([ADDRESS]);

// sendContractTransaction(uint256,uint256,address,uint256,bytes)
export const sendContractTransactionSchema = z.tuple([
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
]);

// sendL1FundedContractTransaction(uint256,uint256,address,bytes)
export const sendL1FundedContractTransactionSchema = z.tuple([
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  ADDRESS.describe('to: address'),
  BYTES.describe('data: bytes'),
]);

// sendL1FundedUnsignedTransaction(uint256,uint256,uint256,address,bytes)
export const sendL1FundedUnsignedTransactionSchema = z.tuple([
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  UINT256.describe('nonce: uint256'),
  ADDRESS.describe('to: address'),
  BYTES.describe('data: bytes'),
]);

// sendL1FundedUnsignedTransactionToFork(uint256,uint256,uint256,address,bytes)
export const sendL1FundedUnsignedTransactionToForkSchema = z.tuple([
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  UINT256.describe('nonce: uint256'),
  ADDRESS.describe('to: address'),
  BYTES.describe('data: bytes'),
]);

// sendL2Message(bytes)
export const sendL2MessageSchema = z.tuple([BYTES.describe('messageData: bytes')]);

// sendL2MessageFromOrigin(bytes)
export const sendL2MessageFromOriginSchema = z.tuple([BYTES.describe('messageData: bytes')]);

// sendUnsignedTransaction(uint256,uint256,uint256,address,uint256,bytes)
export const sendUnsignedTransactionSchema = z.tuple([
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  UINT256.describe('nonce: uint256'),
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
]);

// sendUnsignedTransactionToFork(uint256,uint256,uint256,address,uint256,bytes)
export const sendUnsignedTransactionToForkSchema = z.tuple([
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  UINT256.describe('nonce: uint256'),
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
]);

// sendWithdrawEthToFork(uint256,uint256,uint256,uint256,address)
export const sendWithdrawEthToForkSchema = z.tuple([
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  UINT256.describe('nonce: uint256'),
  UINT256.describe('value: uint256'),
  ADDRESS.describe('withdrawTo: address'),
]);

// sequencerInbox()
export const sequencerInboxSchema = z.tuple([]);

// setAllowList(address[],bool[])
export const setAllowListSchema = z.tuple([
  z.array(ADDRESS).describe('address[]'),
  z.array(BOOL).describe('bool[]'),
]);

// setAllowListEnabled(bool)
export const setAllowListEnabledSchema = z.tuple([BOOL.describe('_allowListEnabled: bool')]);

// unpause()
export const unpauseSchema = z.tuple([]);

// unsafeCreateRetryableTicket(address,uint256,uint256,address,address,uint256,uint256,bytes)
export const unsafeCreateRetryableTicketSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('l2CallValue: uint256'),
  UINT256.describe('maxSubmissionCost: uint256'),
  ADDRESS.describe('excessFeeRefundAddress: address'),
  ADDRESS.describe('callValueRefundAddress: address'),
  UINT256.describe('gasLimit: uint256'),
  UINT256.describe('maxFeePerGas: uint256'),
  BYTES.describe('data: bytes'),
]);

// === Schema table ===

export const schemas = {
  'allowListEnabled': allowListEnabledSchema,
  'bridge': bridgeSchema,
  'calculateRetryableSubmissionFee': calculateRetryableSubmissionFeeSchema,
  'createRetryableTicket': createRetryableTicketSchema,
  'createRetryableTicketNoRefundAliasRewrite': createRetryableTicketNoRefundAliasRewriteSchema,
  'getProxyAdmin': getProxyAdminSchema,
  'initialize': initializeSchema,
  'isAllowed': isAllowedSchema,
  'maxDataSize': maxDataSizeSchema,
  'pause': pauseSchema,
  'paused': pausedSchema,
  'postUpgradeInit': postUpgradeInitSchema,
  'sendContractTransaction': sendContractTransactionSchema,
  'sendL1FundedContractTransaction': sendL1FundedContractTransactionSchema,
  'sendL1FundedUnsignedTransaction': sendL1FundedUnsignedTransactionSchema,
  'sendL1FundedUnsignedTransactionToFork': sendL1FundedUnsignedTransactionToForkSchema,
  'sendL2Message': sendL2MessageSchema,
  'sendL2MessageFromOrigin': sendL2MessageFromOriginSchema,
  'sendUnsignedTransaction': sendUnsignedTransactionSchema,
  'sendUnsignedTransactionToFork': sendUnsignedTransactionToForkSchema,
  'sendWithdrawEthToFork': sendWithdrawEthToForkSchema,
  'sequencerInbox': sequencerInboxSchema,
  'setAllowList': setAllowListSchema,
  'setAllowListEnabled': setAllowListEnabledSchema,
  'unpause': unpauseSchema,
  'unsafeCreateRetryableTicket': unsafeCreateRetryableTicketSchema,
  'allowListEnabled()': allowListEnabledSchema,
  'bridge()': bridgeSchema,
  'calculateRetryableSubmissionFee(uint256,uint256)': calculateRetryableSubmissionFeeSchema,
  'createRetryableTicket(address,uint256,uint256,address,address,uint256,uint256,bytes)':
    createRetryableTicketSchema,
  'createRetryableTicketNoRefundAliasRewrite(address,uint256,uint256,address,address,uint256,uint256,bytes)':
    createRetryableTicketNoRefundAliasRewriteSchema,
  'depositEth()': z.tuple([]),
  'depositEth(uint256)': z.tuple([UINT256]),
  'getProxyAdmin()': getProxyAdminSchema,
  'initialize(address,address)': initializeSchema,
  'isAllowed(address)': isAllowedSchema,
  'maxDataSize()': maxDataSizeSchema,
  'pause()': pauseSchema,
  'paused()': pausedSchema,
  'postUpgradeInit(address)': postUpgradeInitSchema,
  'sendContractTransaction(uint256,uint256,address,uint256,bytes)': sendContractTransactionSchema,
  'sendL1FundedContractTransaction(uint256,uint256,address,bytes)':
    sendL1FundedContractTransactionSchema,
  'sendL1FundedUnsignedTransaction(uint256,uint256,uint256,address,bytes)':
    sendL1FundedUnsignedTransactionSchema,
  'sendL1FundedUnsignedTransactionToFork(uint256,uint256,uint256,address,bytes)':
    sendL1FundedUnsignedTransactionToForkSchema,
  'sendL2Message(bytes)': sendL2MessageSchema,
  'sendL2MessageFromOrigin(bytes)': sendL2MessageFromOriginSchema,
  'sendUnsignedTransaction(uint256,uint256,uint256,address,uint256,bytes)':
    sendUnsignedTransactionSchema,
  'sendUnsignedTransactionToFork(uint256,uint256,uint256,address,uint256,bytes)':
    sendUnsignedTransactionToForkSchema,
  'sendWithdrawEthToFork(uint256,uint256,uint256,uint256,address)': sendWithdrawEthToForkSchema,
  'sequencerInbox()': sequencerInboxSchema,
  'setAllowList(address[],bool[])': setAllowListSchema,
  'setAllowListEnabled(bool)': setAllowListEnabledSchema,
  'unpause()': unpauseSchema,
  'unsafeCreateRetryableTicket(address,uint256,uint256,address,address,uint256,uint256,bytes)':
    unsafeCreateRetryableTicketSchema,
} as const;
