// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// canonicalL2FactoryAddress()
export const canonicalL2FactoryAddressSchema = z.tuple([]);

// createTokenBridge(address,address,uint256,uint256)
export const createTokenBridgeSchema = z.tuple([
  ADDRESS.describe('inbox: address'),
  ADDRESS.describe('rollupOwner: address'),
  UINT256.describe('maxGasForContracts: uint256'),
  UINT256.describe('gasPriceBid: uint256'),
]);

// gasLimitForL2FactoryDeployment()
export const gasLimitForL2FactoryDeploymentSchema = z.tuple([]);

// getRouter(address)
export const getRouterSchema = z.tuple([ADDRESS.describe('inbox: address')]);

// inboxToL1Deployment(address)
export const inboxToL1DeploymentSchema = z.tuple([ADDRESS]);

// inboxToL2Deployment(address)
export const inboxToL2DeploymentSchema = z.tuple([ADDRESS]);

// initialize(address)
export const initializeSchema = z.tuple([ADDRESS.describe('_retryableSender: address')]);

// l1Multicall()
export const l1MulticallSchema = z.tuple([]);

// l1Templates()
export const l1TemplatesSchema = z.tuple([]);

// l1Weth()
export const l1WethSchema = z.tuple([]);

// l2CustomGatewayTemplate()
export const l2CustomGatewayTemplateSchema = z.tuple([]);

// l2MulticallTemplate()
export const l2MulticallTemplateSchema = z.tuple([]);

// l2RouterTemplate()
export const l2RouterTemplateSchema = z.tuple([]);

// l2StandardGatewayTemplate()
export const l2StandardGatewayTemplateSchema = z.tuple([]);

// l2TokenBridgeFactoryTemplate()
export const l2TokenBridgeFactoryTemplateSchema = z.tuple([]);

// l2WethGatewayTemplate()
export const l2WethGatewayTemplateSchema = z.tuple([]);

// l2WethTemplate()
export const l2WethTemplateSchema = z.tuple([]);

// owner()
export const ownerSchema = z.tuple([]);

// renounceOwnership()
export const renounceOwnershipSchema = z.tuple([]);

// retryableSender()
export const retryableSenderSchema = z.tuple([]);

// setDeployment(address,(address,address,address,address,address),(address,address,address,address,address,address,address,address,address))
export const setDeploymentSchema = z.tuple([
  ADDRESS.describe('inbox: address'),
  z
    .strictObject({
      router: ADDRESS.describe('router: address'),
      standardGateway: ADDRESS.describe('standardGateway: address'),
      customGateway: ADDRESS.describe('customGateway: address'),
      wethGateway: ADDRESS.describe('wethGateway: address'),
      weth: ADDRESS.describe('weth: address'),
    })
    .describe('(address,address,address,address,address)'),
  z
    .strictObject({
      router: ADDRESS.describe('router: address'),
      standardGateway: ADDRESS.describe('standardGateway: address'),
      customGateway: ADDRESS.describe('customGateway: address'),
      wethGateway: ADDRESS.describe('wethGateway: address'),
      weth: ADDRESS.describe('weth: address'),
      proxyAdmin: ADDRESS.describe('proxyAdmin: address'),
      beaconProxyFactory: ADDRESS.describe('beaconProxyFactory: address'),
      upgradeExecutor: ADDRESS.describe('upgradeExecutor: address'),
      multicall: ADDRESS.describe('multicall: address'),
    })
    .describe('(address,address,address,address,address,address,address,address,address)'),
]);

// setTemplates((address,address,address,address,address,address,address,address),address,address,address,address,address,address,address,address,address,uint256)
export const setTemplatesSchema = z.tuple([
  z
    .strictObject({
      routerTemplate: ADDRESS.describe('routerTemplate: address'),
      standardGatewayTemplate: ADDRESS.describe('standardGatewayTemplate: address'),
      customGatewayTemplate: ADDRESS.describe('customGatewayTemplate: address'),
      wethGatewayTemplate: ADDRESS.describe('wethGatewayTemplate: address'),
      feeTokenBasedRouterTemplate: ADDRESS.describe('feeTokenBasedRouterTemplate: address'),
      feeTokenBasedStandardGatewayTemplate: ADDRESS.describe(
        'feeTokenBasedStandardGatewayTemplate: address',
      ),
      feeTokenBasedCustomGatewayTemplate: ADDRESS.describe(
        'feeTokenBasedCustomGatewayTemplate: address',
      ),
      upgradeExecutor: ADDRESS.describe('upgradeExecutor: address'),
    })
    .describe('(address,address,address,address,address,address,address,address)'),
  ADDRESS.describe('_l2TokenBridgeFactoryTemplate: address'),
  ADDRESS.describe('_l2RouterTemplate: address'),
  ADDRESS.describe('_l2StandardGatewayTemplate: address'),
  ADDRESS.describe('_l2CustomGatewayTemplate: address'),
  ADDRESS.describe('_l2WethGatewayTemplate: address'),
  ADDRESS.describe('_l2WethTemplate: address'),
  ADDRESS.describe('_l2MulticallTemplate: address'),
  ADDRESS.describe('_l1Weth: address'),
  ADDRESS.describe('_l1Multicall: address'),
  UINT256.describe('_gasLimitForL2FactoryDeployment: uint256'),
]);

// transferOwnership(address)
export const transferOwnershipSchema = z.tuple([ADDRESS.describe('newOwner: address')]);

// === Schema table ===

export const schemas = {
  'canonicalL2FactoryAddress': canonicalL2FactoryAddressSchema,
  'createTokenBridge': createTokenBridgeSchema,
  'gasLimitForL2FactoryDeployment': gasLimitForL2FactoryDeploymentSchema,
  'getRouter': getRouterSchema,
  'inboxToL1Deployment': inboxToL1DeploymentSchema,
  'inboxToL2Deployment': inboxToL2DeploymentSchema,
  'initialize': initializeSchema,
  'l1Multicall': l1MulticallSchema,
  'l1Templates': l1TemplatesSchema,
  'l1Weth': l1WethSchema,
  'l2CustomGatewayTemplate': l2CustomGatewayTemplateSchema,
  'l2MulticallTemplate': l2MulticallTemplateSchema,
  'l2RouterTemplate': l2RouterTemplateSchema,
  'l2StandardGatewayTemplate': l2StandardGatewayTemplateSchema,
  'l2TokenBridgeFactoryTemplate': l2TokenBridgeFactoryTemplateSchema,
  'l2WethGatewayTemplate': l2WethGatewayTemplateSchema,
  'l2WethTemplate': l2WethTemplateSchema,
  'owner': ownerSchema,
  'renounceOwnership': renounceOwnershipSchema,
  'retryableSender': retryableSenderSchema,
  'setDeployment': setDeploymentSchema,
  'setTemplates': setTemplatesSchema,
  'transferOwnership': transferOwnershipSchema,
  'canonicalL2FactoryAddress()': canonicalL2FactoryAddressSchema,
  'createTokenBridge(address,address,uint256,uint256)': createTokenBridgeSchema,
  'gasLimitForL2FactoryDeployment()': gasLimitForL2FactoryDeploymentSchema,
  'getRouter(address)': getRouterSchema,
  'inboxToL1Deployment(address)': inboxToL1DeploymentSchema,
  'inboxToL2Deployment(address)': inboxToL2DeploymentSchema,
  'initialize(address)': initializeSchema,
  'l1Multicall()': l1MulticallSchema,
  'l1Templates()': l1TemplatesSchema,
  'l1Weth()': l1WethSchema,
  'l2CustomGatewayTemplate()': l2CustomGatewayTemplateSchema,
  'l2MulticallTemplate()': l2MulticallTemplateSchema,
  'l2RouterTemplate()': l2RouterTemplateSchema,
  'l2StandardGatewayTemplate()': l2StandardGatewayTemplateSchema,
  'l2TokenBridgeFactoryTemplate()': l2TokenBridgeFactoryTemplateSchema,
  'l2WethGatewayTemplate()': l2WethGatewayTemplateSchema,
  'l2WethTemplate()': l2WethTemplateSchema,
  'owner()': ownerSchema,
  'renounceOwnership()': renounceOwnershipSchema,
  'retryableSender()': retryableSenderSchema,
  'setDeployment(address,(address,address,address,address,address),(address,address,address,address,address,address,address,address,address))':
    setDeploymentSchema,
  'setTemplates((address,address,address,address,address,address,address,address),address,address,address,address,address,address,address,address,address,uint256)':
    setTemplatesSchema,
  'transferOwnership(address)': transferOwnershipSchema,
} as const;
