// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);

// === Function schemas ===

// addBatchPoster(address)
export const addBatchPosterSchema = z.tuple([ADDRESS.describe('newBatchPoster: address')]);

// getBatchPosters()
export const getBatchPostersSchema = z.tuple([]);

// getDefaultAggregator()
export const getDefaultAggregatorSchema = z.tuple([]);

// getFeeCollector(address)
export const getFeeCollectorSchema = z.tuple([ADDRESS.describe('batchPoster: address')]);

// getPreferredAggregator(address)
export const getPreferredAggregatorSchema = z.tuple([ADDRESS.describe('addr: address')]);

// getTxBaseFee(address)
export const getTxBaseFeeSchema = z.tuple([ADDRESS.describe('aggregator: address')]);

// setFeeCollector(address,address)
export const setFeeCollectorSchema = z.tuple([
  ADDRESS.describe('batchPoster: address'),
  ADDRESS.describe('newFeeCollector: address'),
]);

// setTxBaseFee(address,uint256)
export const setTxBaseFeeSchema = z.tuple([
  ADDRESS.describe('aggregator: address'),
  UINT256.describe('feeInL1Gas: uint256'),
]);

// === Schema table ===

export const schemas = {
  'addBatchPoster': addBatchPosterSchema,
  'getBatchPosters': getBatchPostersSchema,
  'getDefaultAggregator': getDefaultAggregatorSchema,
  'getFeeCollector': getFeeCollectorSchema,
  'getPreferredAggregator': getPreferredAggregatorSchema,
  'getTxBaseFee': getTxBaseFeeSchema,
  'setFeeCollector': setFeeCollectorSchema,
  'setTxBaseFee': setTxBaseFeeSchema,
  'addBatchPoster(address)': addBatchPosterSchema,
  'getBatchPosters()': getBatchPostersSchema,
  'getDefaultAggregator()': getDefaultAggregatorSchema,
  'getFeeCollector(address)': getFeeCollectorSchema,
  'getPreferredAggregator(address)': getPreferredAggregatorSchema,
  'getTxBaseFee(address)': getTxBaseFeeSchema,
  'setFeeCollector(address,address)': setFeeCollectorSchema,
  'setTxBaseFee(address,uint256)': setTxBaseFeeSchema,
} as const;
