// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const INT64 = z
  .string()
  .regex(/^-?\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n >= -(1n << 63n) && n <= (1n << 63n) - 1n);
const STRING = z.string();
const UINT16 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 16n) - 1n)
  .transform((b) => Number(b));
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);
const UINT32 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 32n) - 1n)
  .transform((b) => Number(b));
const UINT64 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 64n) - 1n);
const UINT8 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 8n) - 1n)
  .transform((b) => Number(b));

// === Function schemas ===

// addChainOwner(address)
export const addChainOwnerSchema = z.tuple([ADDRESS.describe('newOwner: address')]);

// addWasmCacheManager(address)
export const addWasmCacheManagerSchema = z.tuple([ADDRESS.describe('manager: address')]);

// getAllChainOwners()
export const getAllChainOwnersSchema = z.tuple([]);

// getInfraFeeAccount()
export const getInfraFeeAccountSchema = z.tuple([]);

// getNetworkFeeAccount()
export const getNetworkFeeAccountSchema = z.tuple([]);

// isChainOwner(address)
export const isChainOwnerSchema = z.tuple([ADDRESS.describe('addr: address')]);

// releaseL1PricerSurplusFunds(uint256)
export const releaseL1PricerSurplusFundsSchema = z.tuple([
  UINT256.describe('maxWeiToRelease: uint256'),
]);

// removeChainOwner(address)
export const removeChainOwnerSchema = z.tuple([ADDRESS.describe('ownerToRemove: address')]);

// removeWasmCacheManager(address)
export const removeWasmCacheManagerSchema = z.tuple([ADDRESS.describe('manager: address')]);

// scheduleArbOSUpgrade(uint64,uint64)
export const scheduleArbOSUpgradeSchema = z.tuple([
  UINT64.describe('newVersion: uint64'),
  UINT64.describe('timestamp: uint64'),
]);

// setAmortizedCostCapBips(uint64)
export const setAmortizedCostCapBipsSchema = z.tuple([UINT64.describe('cap: uint64')]);

// setBrotliCompressionLevel(uint64)
export const setBrotliCompressionLevelSchema = z.tuple([UINT64.describe('level: uint64')]);

// setChainConfig(string)
export const setChainConfigSchema = z.tuple([STRING.describe('chainConfig: string')]);

// setInfraFeeAccount(address)
export const setInfraFeeAccountSchema = z.tuple([ADDRESS.describe('newInfraFeeAccount: address')]);

// setInkPrice(uint32)
export const setInkPriceSchema = z.tuple([UINT32.describe('price: uint32')]);

// setL1BaseFeeEstimateInertia(uint64)
export const setL1BaseFeeEstimateInertiaSchema = z.tuple([UINT64.describe('inertia: uint64')]);

// setL1PricePerUnit(uint256)
export const setL1PricePerUnitSchema = z.tuple([UINT256.describe('pricePerUnit: uint256')]);

// setL1PricingEquilibrationUnits(uint256)
export const setL1PricingEquilibrationUnitsSchema = z.tuple([
  UINT256.describe('equilibrationUnits: uint256'),
]);

// setL1PricingInertia(uint64)
export const setL1PricingInertiaSchema = z.tuple([UINT64.describe('inertia: uint64')]);

// setL1PricingRewardRate(uint64)
export const setL1PricingRewardRateSchema = z.tuple([UINT64.describe('weiPerUnit: uint64')]);

// setL1PricingRewardRecipient(address)
export const setL1PricingRewardRecipientSchema = z.tuple([ADDRESS.describe('recipient: address')]);

// setL2BaseFee(uint256)
export const setL2BaseFeeSchema = z.tuple([UINT256.describe('priceInWei: uint256')]);

// setL2GasBacklogTolerance(uint64)
export const setL2GasBacklogToleranceSchema = z.tuple([UINT64.describe('sec: uint64')]);

// setL2GasPricingInertia(uint64)
export const setL2GasPricingInertiaSchema = z.tuple([UINT64.describe('sec: uint64')]);

// setMaxTxGasLimit(uint64)
export const setMaxTxGasLimitSchema = z.tuple([UINT64.describe('limit: uint64')]);

// setMinimumL2BaseFee(uint256)
export const setMinimumL2BaseFeeSchema = z.tuple([UINT256.describe('priceInWei: uint256')]);

// setNetworkFeeAccount(address)
export const setNetworkFeeAccountSchema = z.tuple([
  ADDRESS.describe('newNetworkFeeAccount: address'),
]);

// setPerBatchGasCharge(int64)
export const setPerBatchGasChargeSchema = z.tuple([INT64.describe('cost: int64')]);

// setSpeedLimit(uint64)
export const setSpeedLimitSchema = z.tuple([UINT64.describe('limit: uint64')]);

// setWasmBlockCacheSize(uint16)
export const setWasmBlockCacheSizeSchema = z.tuple([UINT16.describe('count: uint16')]);

// setWasmExpiryDays(uint16)
export const setWasmExpiryDaysSchema = z.tuple([UINT16.describe('_days: uint16')]);

// setWasmFreePages(uint16)
export const setWasmFreePagesSchema = z.tuple([UINT16.describe('pages: uint16')]);

// setWasmInitCostScalar(uint64)
export const setWasmInitCostScalarSchema = z.tuple([UINT64.describe('percent: uint64')]);

// setWasmKeepaliveDays(uint16)
export const setWasmKeepaliveDaysSchema = z.tuple([UINT16.describe('_days: uint16')]);

// setWasmMaxStackDepth(uint32)
export const setWasmMaxStackDepthSchema = z.tuple([UINT32.describe('depth: uint32')]);

// setWasmMinInitGas(uint8,uint16)
export const setWasmMinInitGasSchema = z.tuple([
  UINT8.describe('gas: uint8'),
  UINT16.describe('cached: uint16'),
]);

// setWasmPageGas(uint16)
export const setWasmPageGasSchema = z.tuple([UINT16.describe('gas: uint16')]);

// setWasmPageLimit(uint16)
export const setWasmPageLimitSchema = z.tuple([UINT16.describe('limit: uint16')]);

// === Schema table ===

export const schemas = {
  'addChainOwner': addChainOwnerSchema,
  'addWasmCacheManager': addWasmCacheManagerSchema,
  'getAllChainOwners': getAllChainOwnersSchema,
  'getInfraFeeAccount': getInfraFeeAccountSchema,
  'getNetworkFeeAccount': getNetworkFeeAccountSchema,
  'isChainOwner': isChainOwnerSchema,
  'releaseL1PricerSurplusFunds': releaseL1PricerSurplusFundsSchema,
  'removeChainOwner': removeChainOwnerSchema,
  'removeWasmCacheManager': removeWasmCacheManagerSchema,
  'scheduleArbOSUpgrade': scheduleArbOSUpgradeSchema,
  'setAmortizedCostCapBips': setAmortizedCostCapBipsSchema,
  'setBrotliCompressionLevel': setBrotliCompressionLevelSchema,
  'setChainConfig': setChainConfigSchema,
  'setInfraFeeAccount': setInfraFeeAccountSchema,
  'setInkPrice': setInkPriceSchema,
  'setL1BaseFeeEstimateInertia': setL1BaseFeeEstimateInertiaSchema,
  'setL1PricePerUnit': setL1PricePerUnitSchema,
  'setL1PricingEquilibrationUnits': setL1PricingEquilibrationUnitsSchema,
  'setL1PricingInertia': setL1PricingInertiaSchema,
  'setL1PricingRewardRate': setL1PricingRewardRateSchema,
  'setL1PricingRewardRecipient': setL1PricingRewardRecipientSchema,
  'setL2BaseFee': setL2BaseFeeSchema,
  'setL2GasBacklogTolerance': setL2GasBacklogToleranceSchema,
  'setL2GasPricingInertia': setL2GasPricingInertiaSchema,
  'setMaxTxGasLimit': setMaxTxGasLimitSchema,
  'setMinimumL2BaseFee': setMinimumL2BaseFeeSchema,
  'setNetworkFeeAccount': setNetworkFeeAccountSchema,
  'setPerBatchGasCharge': setPerBatchGasChargeSchema,
  'setSpeedLimit': setSpeedLimitSchema,
  'setWasmBlockCacheSize': setWasmBlockCacheSizeSchema,
  'setWasmExpiryDays': setWasmExpiryDaysSchema,
  'setWasmFreePages': setWasmFreePagesSchema,
  'setWasmInitCostScalar': setWasmInitCostScalarSchema,
  'setWasmKeepaliveDays': setWasmKeepaliveDaysSchema,
  'setWasmMaxStackDepth': setWasmMaxStackDepthSchema,
  'setWasmMinInitGas': setWasmMinInitGasSchema,
  'setWasmPageGas': setWasmPageGasSchema,
  'setWasmPageLimit': setWasmPageLimitSchema,
  'addChainOwner(address)': addChainOwnerSchema,
  'addWasmCacheManager(address)': addWasmCacheManagerSchema,
  'getAllChainOwners()': getAllChainOwnersSchema,
  'getInfraFeeAccount()': getInfraFeeAccountSchema,
  'getNetworkFeeAccount()': getNetworkFeeAccountSchema,
  'isChainOwner(address)': isChainOwnerSchema,
  'releaseL1PricerSurplusFunds(uint256)': releaseL1PricerSurplusFundsSchema,
  'removeChainOwner(address)': removeChainOwnerSchema,
  'removeWasmCacheManager(address)': removeWasmCacheManagerSchema,
  'scheduleArbOSUpgrade(uint64,uint64)': scheduleArbOSUpgradeSchema,
  'setAmortizedCostCapBips(uint64)': setAmortizedCostCapBipsSchema,
  'setBrotliCompressionLevel(uint64)': setBrotliCompressionLevelSchema,
  'setChainConfig(string)': setChainConfigSchema,
  'setInfraFeeAccount(address)': setInfraFeeAccountSchema,
  'setInkPrice(uint32)': setInkPriceSchema,
  'setL1BaseFeeEstimateInertia(uint64)': setL1BaseFeeEstimateInertiaSchema,
  'setL1PricePerUnit(uint256)': setL1PricePerUnitSchema,
  'setL1PricingEquilibrationUnits(uint256)': setL1PricingEquilibrationUnitsSchema,
  'setL1PricingInertia(uint64)': setL1PricingInertiaSchema,
  'setL1PricingRewardRate(uint64)': setL1PricingRewardRateSchema,
  'setL1PricingRewardRecipient(address)': setL1PricingRewardRecipientSchema,
  'setL2BaseFee(uint256)': setL2BaseFeeSchema,
  'setL2GasBacklogTolerance(uint64)': setL2GasBacklogToleranceSchema,
  'setL2GasPricingInertia(uint64)': setL2GasPricingInertiaSchema,
  'setMaxTxGasLimit(uint64)': setMaxTxGasLimitSchema,
  'setMinimumL2BaseFee(uint256)': setMinimumL2BaseFeeSchema,
  'setNetworkFeeAccount(address)': setNetworkFeeAccountSchema,
  'setPerBatchGasCharge(int64)': setPerBatchGasChargeSchema,
  'setSpeedLimit(uint64)': setSpeedLimitSchema,
  'setWasmBlockCacheSize(uint16)': setWasmBlockCacheSizeSchema,
  'setWasmExpiryDays(uint16)': setWasmExpiryDaysSchema,
  'setWasmFreePages(uint16)': setWasmFreePagesSchema,
  'setWasmInitCostScalar(uint64)': setWasmInitCostScalarSchema,
  'setWasmKeepaliveDays(uint16)': setWasmKeepaliveDaysSchema,
  'setWasmMaxStackDepth(uint32)': setWasmMaxStackDepthSchema,
  'setWasmMinInitGas(uint8,uint16)': setWasmMinInitGasSchema,
  'setWasmPageGas(uint16)': setWasmPageGasSchema,
  'setWasmPageLimit(uint16)': setWasmPageLimitSchema,
} as const;
