// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const INT64 = z
  .string()
  .regex(/^-?\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n >= -(1n << 63n) && n <= (1n << 63n) - 1n);
const STRING = z.string();
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);
const UINT64 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 64n) - 1n);

// === Function schemas ===

// addChainOwner(address)
export const addChainOwnerSchema = z.tuple([ADDRESS.describe('newOwner: address')]);

// getAllChainOwners()
export const getAllChainOwnersSchema = z.tuple([]);

// getInfraFeeAccount()
export const getInfraFeeAccountSchema = z.tuple([]);

// getNetworkFeeAccount()
export const getNetworkFeeAccountSchema = z.tuple([]);

// isChainOwner(address)
export const isChainOwnerSchema = z.tuple([ADDRESS.describe('addr: address')]);

// releaseL1PricerSurplusFunds(uint256)
export const releaseL1PricerSurplusFundsSchema = z.tuple([
  UINT256.describe('maxWeiToRelease: uint256'),
]);

// removeChainOwner(address)
export const removeChainOwnerSchema = z.tuple([ADDRESS.describe('ownerToRemove: address')]);

// scheduleArbOSUpgrade(uint64,uint64)
export const scheduleArbOSUpgradeSchema = z.tuple([
  UINT64.describe('newVersion: uint64'),
  UINT64.describe('timestamp: uint64'),
]);

// setAmortizedCostCapBips(uint64)
export const setAmortizedCostCapBipsSchema = z.tuple([UINT64.describe('cap: uint64')]);

// setBrotliCompressionLevel(uint64)
export const setBrotliCompressionLevelSchema = z.tuple([UINT64.describe('level: uint64')]);

// setChainConfig(string)
export const setChainConfigSchema = z.tuple([STRING.describe('chainConfig: string')]);

// setInfraFeeAccount(address)
export const setInfraFeeAccountSchema = z.tuple([ADDRESS.describe('newInfraFeeAccount: address')]);

// setL1BaseFeeEstimateInertia(uint64)
export const setL1BaseFeeEstimateInertiaSchema = z.tuple([UINT64.describe('inertia: uint64')]);

// setL1PricePerUnit(uint256)
export const setL1PricePerUnitSchema = z.tuple([UINT256.describe('pricePerUnit: uint256')]);

// setL1PricingEquilibrationUnits(uint256)
export const setL1PricingEquilibrationUnitsSchema = z.tuple([
  UINT256.describe('equilibrationUnits: uint256'),
]);

// setL1PricingInertia(uint64)
export const setL1PricingInertiaSchema = z.tuple([UINT64.describe('inertia: uint64')]);

// setL1PricingRewardRate(uint64)
export const setL1PricingRewardRateSchema = z.tuple([UINT64.describe('weiPerUnit: uint64')]);

// setL1PricingRewardRecipient(address)
export const setL1PricingRewardRecipientSchema = z.tuple([ADDRESS.describe('recipient: address')]);

// setL2BaseFee(uint256)
export const setL2BaseFeeSchema = z.tuple([UINT256.describe('priceInWei: uint256')]);

// setL2GasBacklogTolerance(uint64)
export const setL2GasBacklogToleranceSchema = z.tuple([UINT64.describe('sec: uint64')]);

// setL2GasPricingInertia(uint64)
export const setL2GasPricingInertiaSchema = z.tuple([UINT64.describe('sec: uint64')]);

// setMaxTxGasLimit(uint64)
export const setMaxTxGasLimitSchema = z.tuple([UINT64.describe('limit: uint64')]);

// setMinimumL2BaseFee(uint256)
export const setMinimumL2BaseFeeSchema = z.tuple([UINT256.describe('priceInWei: uint256')]);

// setNetworkFeeAccount(address)
export const setNetworkFeeAccountSchema = z.tuple([
  ADDRESS.describe('newNetworkFeeAccount: address'),
]);

// setPerBatchGasCharge(int64)
export const setPerBatchGasChargeSchema = z.tuple([INT64.describe('cost: int64')]);

// setSpeedLimit(uint64)
export const setSpeedLimitSchema = z.tuple([UINT64.describe('limit: uint64')]);

// === Schema table ===

export const schemas = {
  'addChainOwner': addChainOwnerSchema,
  'getAllChainOwners': getAllChainOwnersSchema,
  'getInfraFeeAccount': getInfraFeeAccountSchema,
  'getNetworkFeeAccount': getNetworkFeeAccountSchema,
  'isChainOwner': isChainOwnerSchema,
  'releaseL1PricerSurplusFunds': releaseL1PricerSurplusFundsSchema,
  'removeChainOwner': removeChainOwnerSchema,
  'scheduleArbOSUpgrade': scheduleArbOSUpgradeSchema,
  'setAmortizedCostCapBips': setAmortizedCostCapBipsSchema,
  'setBrotliCompressionLevel': setBrotliCompressionLevelSchema,
  'setChainConfig': setChainConfigSchema,
  'setInfraFeeAccount': setInfraFeeAccountSchema,
  'setL1BaseFeeEstimateInertia': setL1BaseFeeEstimateInertiaSchema,
  'setL1PricePerUnit': setL1PricePerUnitSchema,
  'setL1PricingEquilibrationUnits': setL1PricingEquilibrationUnitsSchema,
  'setL1PricingInertia': setL1PricingInertiaSchema,
  'setL1PricingRewardRate': setL1PricingRewardRateSchema,
  'setL1PricingRewardRecipient': setL1PricingRewardRecipientSchema,
  'setL2BaseFee': setL2BaseFeeSchema,
  'setL2GasBacklogTolerance': setL2GasBacklogToleranceSchema,
  'setL2GasPricingInertia': setL2GasPricingInertiaSchema,
  'setMaxTxGasLimit': setMaxTxGasLimitSchema,
  'setMinimumL2BaseFee': setMinimumL2BaseFeeSchema,
  'setNetworkFeeAccount': setNetworkFeeAccountSchema,
  'setPerBatchGasCharge': setPerBatchGasChargeSchema,
  'setSpeedLimit': setSpeedLimitSchema,
  'addChainOwner(address)': addChainOwnerSchema,
  'getAllChainOwners()': getAllChainOwnersSchema,
  'getInfraFeeAccount()': getInfraFeeAccountSchema,
  'getNetworkFeeAccount()': getNetworkFeeAccountSchema,
  'isChainOwner(address)': isChainOwnerSchema,
  'releaseL1PricerSurplusFunds(uint256)': releaseL1PricerSurplusFundsSchema,
  'removeChainOwner(address)': removeChainOwnerSchema,
  'scheduleArbOSUpgrade(uint64,uint64)': scheduleArbOSUpgradeSchema,
  'setAmortizedCostCapBips(uint64)': setAmortizedCostCapBipsSchema,
  'setBrotliCompressionLevel(uint64)': setBrotliCompressionLevelSchema,
  'setChainConfig(string)': setChainConfigSchema,
  'setInfraFeeAccount(address)': setInfraFeeAccountSchema,
  'setL1BaseFeeEstimateInertia(uint64)': setL1BaseFeeEstimateInertiaSchema,
  'setL1PricePerUnit(uint256)': setL1PricePerUnitSchema,
  'setL1PricingEquilibrationUnits(uint256)': setL1PricingEquilibrationUnitsSchema,
  'setL1PricingInertia(uint64)': setL1PricingInertiaSchema,
  'setL1PricingRewardRate(uint64)': setL1PricingRewardRateSchema,
  'setL1PricingRewardRecipient(address)': setL1PricingRewardRecipientSchema,
  'setL2BaseFee(uint256)': setL2BaseFeeSchema,
  'setL2GasBacklogTolerance(uint64)': setL2GasBacklogToleranceSchema,
  'setL2GasPricingInertia(uint64)': setL2GasPricingInertiaSchema,
  'setMaxTxGasLimit(uint64)': setMaxTxGasLimitSchema,
  'setMinimumL2BaseFee(uint256)': setMinimumL2BaseFeeSchema,
  'setNetworkFeeAccount(address)': setNetworkFeeAccountSchema,
  'setPerBatchGasCharge(int64)': setPerBatchGasChargeSchema,
  'setSpeedLimit(uint64)': setSpeedLimitSchema,
} as const;
