// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const BYTES = z
  .string()
  .regex(/^0x([0-9a-fA-F]{2})*$/)
  .transform((v) => v as `0x${string}`);
const BYTES32 = z
  .string()
  .regex(/^0x[0-9a-fA-F]{64}$/)
  .transform((v) => v as `0x${string}`);
const UINT256 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 256n) - 1n);
const UINT8 = z
  .string()
  .regex(/^\d+$/)
  .transform((v) => BigInt(v))
  .refine((n) => n <= (1n << 8n) - 1n)
  .transform((b) => Number(b));

// === Function schemas ===

// VERSION()
export const VERSIONSchema = z.tuple([]);

// addOwnerWithThreshold(address,uint256)
export const addOwnerWithThresholdSchema = z.tuple([
  ADDRESS.describe('owner: address'),
  UINT256.describe('_threshold: uint256'),
]);

// approveHash(bytes32)
export const approveHashSchema = z.tuple([BYTES32.describe('hashToApprove: bytes32')]);

// approvedHashes(address,bytes32)
export const approvedHashesSchema = z.tuple([ADDRESS, BYTES32]);

// changeThreshold(uint256)
export const changeThresholdSchema = z.tuple([UINT256.describe('_threshold: uint256')]);

// checkNSignatures(bytes32,bytes,bytes,uint256)
export const checkNSignaturesSchema = z.tuple([
  BYTES32.describe('dataHash: bytes32'),
  BYTES.describe('data: bytes'),
  BYTES.describe('signatures: bytes'),
  UINT256.describe('requiredSignatures: uint256'),
]);

// checkSignatures(bytes32,bytes,bytes)
export const checkSignaturesSchema = z.tuple([
  BYTES32.describe('dataHash: bytes32'),
  BYTES.describe('data: bytes'),
  BYTES.describe('signatures: bytes'),
]);

// disableModule(address,address)
export const disableModuleSchema = z.tuple([
  ADDRESS.describe('prevModule: address'),
  ADDRESS.describe('module: address'),
]);

// domainSeparator()
export const domainSeparatorSchema = z.tuple([]);

// enableModule(address)
export const enableModuleSchema = z.tuple([ADDRESS.describe('module: address')]);

// encodeTransactionData(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,uint256)
export const encodeTransactionDataSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
  UINT8.describe('operation: uint8'),
  UINT256.describe('safeTxGas: uint256'),
  UINT256.describe('baseGas: uint256'),
  UINT256.describe('gasPrice: uint256'),
  ADDRESS.describe('gasToken: address'),
  ADDRESS.describe('refundReceiver: address'),
  UINT256.describe('_nonce: uint256'),
]);

// execTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes)
export const execTransactionSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
  UINT8.describe('operation: uint8'),
  UINT256.describe('safeTxGas: uint256'),
  UINT256.describe('baseGas: uint256'),
  UINT256.describe('gasPrice: uint256'),
  ADDRESS.describe('gasToken: address'),
  ADDRESS.describe('refundReceiver: address'),
  BYTES.describe('signatures: bytes'),
]);

// execTransactionFromModule(address,uint256,bytes,uint8)
export const execTransactionFromModuleSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
  UINT8.describe('operation: uint8'),
]);

// execTransactionFromModuleReturnData(address,uint256,bytes,uint8)
export const execTransactionFromModuleReturnDataSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
  UINT8.describe('operation: uint8'),
]);

// getChainId()
export const getChainIdSchema = z.tuple([]);

// getModulesPaginated(address,uint256)
export const getModulesPaginatedSchema = z.tuple([
  ADDRESS.describe('start: address'),
  UINT256.describe('pageSize: uint256'),
]);

// getOwners()
export const getOwnersSchema = z.tuple([]);

// getStorageAt(uint256,uint256)
export const getStorageAtSchema = z.tuple([
  UINT256.describe('offset: uint256'),
  UINT256.describe('length: uint256'),
]);

// getThreshold()
export const getThresholdSchema = z.tuple([]);

// getTransactionHash(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,uint256)
export const getTransactionHashSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
  UINT8.describe('operation: uint8'),
  UINT256.describe('safeTxGas: uint256'),
  UINT256.describe('baseGas: uint256'),
  UINT256.describe('gasPrice: uint256'),
  ADDRESS.describe('gasToken: address'),
  ADDRESS.describe('refundReceiver: address'),
  UINT256.describe('_nonce: uint256'),
]);

// isModuleEnabled(address)
export const isModuleEnabledSchema = z.tuple([ADDRESS.describe('module: address')]);

// isOwner(address)
export const isOwnerSchema = z.tuple([ADDRESS.describe('owner: address')]);

// nonce()
export const nonceSchema = z.tuple([]);

// removeOwner(address,address,uint256)
export const removeOwnerSchema = z.tuple([
  ADDRESS.describe('prevOwner: address'),
  ADDRESS.describe('owner: address'),
  UINT256.describe('_threshold: uint256'),
]);

// requiredTxGas(address,uint256,bytes,uint8)
export const requiredTxGasSchema = z.tuple([
  ADDRESS.describe('to: address'),
  UINT256.describe('value: uint256'),
  BYTES.describe('data: bytes'),
  UINT8.describe('operation: uint8'),
]);

// setFallbackHandler(address)
export const setFallbackHandlerSchema = z.tuple([ADDRESS.describe('handler: address')]);

// setGuard(address)
export const setGuardSchema = z.tuple([ADDRESS.describe('guard: address')]);

// setup(address[],uint256,address,bytes,address,address,uint256,address)
export const setupSchema = z.tuple([
  z.array(ADDRESS).describe('address[]'),
  UINT256.describe('_threshold: uint256'),
  ADDRESS.describe('to: address'),
  BYTES.describe('data: bytes'),
  ADDRESS.describe('fallbackHandler: address'),
  ADDRESS.describe('paymentToken: address'),
  UINT256.describe('payment: uint256'),
  ADDRESS.describe('paymentReceiver: address'),
]);

// signedMessages(bytes32)
export const signedMessagesSchema = z.tuple([BYTES32]);

// simulateAndRevert(address,bytes)
export const simulateAndRevertSchema = z.tuple([
  ADDRESS.describe('targetContract: address'),
  BYTES.describe('calldataPayload: bytes'),
]);

// swapOwner(address,address,address)
export const swapOwnerSchema = z.tuple([
  ADDRESS.describe('prevOwner: address'),
  ADDRESS.describe('oldOwner: address'),
  ADDRESS.describe('newOwner: address'),
]);

// === Schema table ===

export const schemas = {
  'VERSION': VERSIONSchema,
  'addOwnerWithThreshold': addOwnerWithThresholdSchema,
  'approveHash': approveHashSchema,
  'approvedHashes': approvedHashesSchema,
  'changeThreshold': changeThresholdSchema,
  'checkNSignatures': checkNSignaturesSchema,
  'checkSignatures': checkSignaturesSchema,
  'disableModule': disableModuleSchema,
  'domainSeparator': domainSeparatorSchema,
  'enableModule': enableModuleSchema,
  'encodeTransactionData': encodeTransactionDataSchema,
  'execTransaction': execTransactionSchema,
  'execTransactionFromModule': execTransactionFromModuleSchema,
  'execTransactionFromModuleReturnData': execTransactionFromModuleReturnDataSchema,
  'getChainId': getChainIdSchema,
  'getModulesPaginated': getModulesPaginatedSchema,
  'getOwners': getOwnersSchema,
  'getStorageAt': getStorageAtSchema,
  'getThreshold': getThresholdSchema,
  'getTransactionHash': getTransactionHashSchema,
  'isModuleEnabled': isModuleEnabledSchema,
  'isOwner': isOwnerSchema,
  'nonce': nonceSchema,
  'removeOwner': removeOwnerSchema,
  'requiredTxGas': requiredTxGasSchema,
  'setFallbackHandler': setFallbackHandlerSchema,
  'setGuard': setGuardSchema,
  'setup': setupSchema,
  'signedMessages': signedMessagesSchema,
  'simulateAndRevert': simulateAndRevertSchema,
  'swapOwner': swapOwnerSchema,
  'VERSION()': VERSIONSchema,
  'addOwnerWithThreshold(address,uint256)': addOwnerWithThresholdSchema,
  'approveHash(bytes32)': approveHashSchema,
  'approvedHashes(address,bytes32)': approvedHashesSchema,
  'changeThreshold(uint256)': changeThresholdSchema,
  'checkNSignatures(bytes32,bytes,bytes,uint256)': checkNSignaturesSchema,
  'checkSignatures(bytes32,bytes,bytes)': checkSignaturesSchema,
  'disableModule(address,address)': disableModuleSchema,
  'domainSeparator()': domainSeparatorSchema,
  'enableModule(address)': enableModuleSchema,
  'encodeTransactionData(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,uint256)':
    encodeTransactionDataSchema,
  'execTransaction(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,bytes)':
    execTransactionSchema,
  'execTransactionFromModule(address,uint256,bytes,uint8)': execTransactionFromModuleSchema,
  'execTransactionFromModuleReturnData(address,uint256,bytes,uint8)':
    execTransactionFromModuleReturnDataSchema,
  'getChainId()': getChainIdSchema,
  'getModulesPaginated(address,uint256)': getModulesPaginatedSchema,
  'getOwners()': getOwnersSchema,
  'getStorageAt(uint256,uint256)': getStorageAtSchema,
  'getThreshold()': getThresholdSchema,
  'getTransactionHash(address,uint256,bytes,uint8,uint256,uint256,uint256,address,address,uint256)':
    getTransactionHashSchema,
  'isModuleEnabled(address)': isModuleEnabledSchema,
  'isOwner(address)': isOwnerSchema,
  'nonce()': nonceSchema,
  'removeOwner(address,address,uint256)': removeOwnerSchema,
  'requiredTxGas(address,uint256,bytes,uint8)': requiredTxGasSchema,
  'setFallbackHandler(address)': setFallbackHandlerSchema,
  'setGuard(address)': setGuardSchema,
  'setup(address[],uint256,address,bytes,address,address,uint256,address)': setupSchema,
  'signedMessages(bytes32)': signedMessagesSchema,
  'simulateAndRevert(address,bytes)': simulateAndRevertSchema,
  'swapOwner(address,address,address)': swapOwnerSchema,
} as const;
