// Generated by abi-to-zod@0.2.0

import { z } from 'zod';

// === Primitive schemas ===

const ADDRESS = z
  .string()
  .regex(/^0x[0-9a-fA-F]{40}$/)
  .transform((v) => v as `0x${string}`);
const BYTES = z
  .string()
  .regex(/^0x([0-9a-fA-F]{2})*$/)
  .transform((v) => v as `0x${string}`);
const BYTES32 = z
  .string()
  .regex(/^0x[0-9a-fA-F]{64}$/)
  .transform((v) => v as `0x${string}`);

// === Function schemas ===

// execute(address,bytes)
export const executeSchema = z.tuple([
  ADDRESS.describe('upgrade: address'),
  BYTES.describe('upgradeCallData: bytes'),
]);

// executeCall(address,bytes)
export const executeCallSchema = z.tuple([
  ADDRESS.describe('target: address'),
  BYTES.describe('targetCallData: bytes'),
]);

// grantRole(bytes32,address)
export const grantRoleSchema = z.tuple([
  BYTES32.describe('role: bytes32'),
  ADDRESS.describe('account: address'),
]);

// hasRole(bytes32,address)
export const hasRoleSchema = z.tuple([
  BYTES32.describe('role: bytes32'),
  ADDRESS.describe('account: address'),
]);

// revokeRole(bytes32,address)
export const revokeRoleSchema = z.tuple([
  BYTES32.describe('role: bytes32'),
  ADDRESS.describe('account: address'),
]);

// === Schema table ===

export const schemas = {
  'execute': executeSchema,
  'executeCall': executeCallSchema,
  'grantRole': grantRoleSchema,
  'hasRole': hasRoleSchema,
  'revokeRole': revokeRoleSchema,
  'execute(address,bytes)': executeSchema,
  'executeCall(address,bytes)': executeCallSchema,
  'grantRole(bytes32,address)': grantRoleSchema,
  'hasRole(bytes32,address)': hasRoleSchema,
  'revokeRole(bytes32,address)': revokeRoleSchema,
} as const;
