FROM node:20-bullseye-slim
RUN apt-get update && \
    apt-get install -y git python3 build-essential && \
    rm -rf /var/lib/apt/lists/*
WORKDIR /workspace
RUN git init . \
    && git remote add origin https://github.com/OffchainLabs/token-bridge-contracts.git \
    && git fetch --depth 1 origin 5975d8f7360816341be7f94fd333ef240f4aec23 \
    && git checkout --detach FETCH_HEAD
RUN yarn install --frozen-lockfile
RUN yarn build
ENTRYPOINT ["yarn"]
